/**
 * ej2 source
 */
import * as _barcodegenerator from '../barcode-generator';
import * as _base from '../base';
import * as _buttons from '../buttons';
import * as _calendars from '../calendars';
import * as _charts from '../charts';
import * as _circulargauge from '../circulargauge';
import * as _compression from '../compression';
import * as _data from '../data';
import * as _diagrams from '../diagrams';
import * as _documenteditor from '../documenteditor';
import * as _drawings from '../drawings';
import * as _dropdowns from '../dropdowns';
import * as _excelexport from '../excel-export';
import * as _fileutils from '../file-utils';
import * as _filemanager from '../filemanager';
import * as _gantt from '../gantt';
import * as _grids from '../grids';
import * as _heatmap from '../heatmap';
import * as _index from '../index';
import * as _inplaceeditor from '../inplace-editor';
import * as _inputs from '../inputs';
import * as _kanban from '../kanban';
import * as _layouts from '../layouts';
import * as _lineargauge from '../lineargauge';
import * as _lists from '../lists';
import * as _maps from '../maps';
import * as _navigations from '../navigations';
import * as _notifications from '../notifications';
import * as _officechart from '../office-chart';
import * as _pdfexport from '../pdf-export';
import * as _pdfviewer from '../pdfviewer';
import * as _pivotview from '../pivotview';
import * as _popups from '../popups';
import * as _progressbar from '../progressbar';
import * as _querybuilder from '../querybuilder';
import * as _richtexteditor from '../richtexteditor';
import * as _schedule from '../schedule';
import * as _splitbuttons from '../splitbuttons';
import * as _spreadsheet from '../spreadsheet';
import * as _svgbase from '../svg-base';
import * as _treegrid from '../treegrid';
import * as _treemap from '../treemap';

export declare namespace ej {
    const barcodegenerator: typeof _barcodegenerator;
    const base: typeof _base;
    const buttons: typeof _buttons;
    const calendars: typeof _calendars;
    const charts: typeof _charts;
    const circulargauge: typeof _circulargauge;
    const compression: typeof _compression;
    const data: typeof _data;
    const diagrams: typeof _diagrams;
    const documenteditor: typeof _documenteditor;
    const drawings: typeof _drawings;
    const dropdowns: typeof _dropdowns;
    const excelexport: typeof _excelexport;
    const fileutils: typeof _fileutils;
    const filemanager: typeof _filemanager;
    const gantt: typeof _gantt;
    const grids: typeof _grids;
    const heatmap: typeof _heatmap;
    const index: typeof _index;
    const inplaceeditor: typeof _inplaceeditor;
    const inputs: typeof _inputs;
    const kanban: typeof _kanban;
    const layouts: typeof _layouts;
    const lineargauge: typeof _lineargauge;
    const lists: typeof _lists;
    const maps: typeof _maps;
    const navigations: typeof _navigations;
    const notifications: typeof _notifications;
    const officechart: typeof _officechart;
    const pdfexport: typeof _pdfexport;
    const pdfviewer: typeof _pdfviewer;
    const pivotview: typeof _pivotview;
    const popups: typeof _popups;
    const progressbar: typeof _progressbar;
    const querybuilder: typeof _querybuilder;
    const richtexteditor: typeof _richtexteditor;
    const schedule: typeof _schedule;
    const splitbuttons: typeof _splitbuttons;
    const spreadsheet: typeof _spreadsheet;
    const svgbase: typeof _svgbase;
    const treegrid: typeof _treegrid;
    const treemap: typeof _treemap;
}
