xcopy /q /y  "wwwroot\css\roboto.css" "Excel\wwwroot\css\"
xcopy /q /y  "wwwroot\css\site.css" "Excel\wwwroot\css\"
xcopy /q /y  "wwwroot\css\sidebar" "Excel\wwwroot\css\sidebar\"
xcopy /q /y  "wwwroot\css\sidebar\fonts" "Excel\wwwroot\css\sidebar\fonts\"
xcopy /q /y  "wwwroot\css\sidebar\icons" "Excel\wwwroot\css\sidebar\icons\"
xcopy /q /y  "wwwroot\css\sidebar\icons\fonts" "Excel\wwwroot\css\sidebar\icons\fonts\"
xcopy /q /y  "wwwroot\css\uploader" "Excel\wwwroot\css\uploader\"
xcopy /q /y  "wwwroot\grid\adaptive-layout.css" "Excel\wwwroot\grid\"
xcopy /q /y  "wwwroot\images\XlsIO" "Excel\wwwroot\images\XlSIO\"
xcopy /q /y  "wwwroot\lib\signalr" "Excel\wwwroot\lib\signalr\"
xcopy /q /y  "wwwroot\scripts\documenteditor" "Excel\wwwroot\scripts\documenteditor\"
xcopy /q /y  "wwwroot\scripts\cldr-data" "Excel\wwwroot\scripts\cldr-data\"
xcopy /q /y  "wwwroot\scripts\cldr-data\main" "Excel\wwwroot\scripts\cldr-data\main\"
xcopy /q /y  "wwwroot\scripts\cldr-data\main\ar\" "Excel\wwwroot\scripts\cldr-data\main\ar\"
xcopy /q /y  "wwwroot\scripts\cldr-data\main\de\" "Excel\wwwroot\scripts\cldr-data\main\de\"
xcopy /q /y  "wwwroot\scripts\cldr-data\main\en\" "Excel\wwwroot\scripts\cldr-data\main\en\"
xcopy /q /y  "wwwroot\scripts\cldr-data\main\fr-CH\" "Excel\wwwroot\scripts\cldr-data\main\fr-CH\"
xcopy /q /y  "wwwroot\scripts\cldr-data\main\he\" "Excel\wwwroot\scripts\cldr-data\main\he\"
xcopy /q /y  "wwwroot\scripts\cldr-data\main\vi\" "Excel\wwwroot\scripts\cldr-data\main\vi\"
xcopy /q /y  "wwwroot\scripts\cldr-data\main\zh\" "Excel\wwwroot\scripts\cldr-data\main\zh\"
xcopy /q /y  "wwwroot\scripts\cldr-data\supplemental" "Excel\wwwroot\scripts\cldr-data\supplemental\"
xcopy /q /y  "wwwroot\scripts\locale" "Excel\wwwroot\scripts\locale\"
xcopy /q /y  "wwwroot\scripts" "Excel\wwwroot\scripts\"
xcopy /q /y  "wwwroot\styles\file-manager" "Excel\wwwroot\styles\file-manager\"
xcopy /q /y  "wwwroot\styles\file-manager\images" "Excel\wwwroot\styles\file-manager\images\"
xcopy /q /y  "wwwroot\styles\images" "Excel\wwwroot\styles\images\"
xcopy /q /y  "wwwroot\styles" "Excel\wwwroot\styles\"
xcopy /q /y  "wwwroot\styles\images\sb-icons" "Excel\wwwroot\styles\images\sb-icons\"
xcopy /q /y  "wwwroot\styles\images\sb-icons\fonts" "Excel\wwwroot\styles\images\sb-icons\fonts\"
xcopy /q /y  "wwwroot\XlsIO" "Excel\wwwroot\XlsIO\"
xcopy /q /y  "wwwroot" "Excel\wwwroot\"
xcopy /q /y  "Controllers\Excel" "Excel\Controllers\Excel\"
xcopy /q /y  "Controllers\Spreadsheet" "Excel\Controllers\Spreadsheet\"
xcopy /q /y  "Controllers\HomeController.cs" "Excel\Controllers\"
xcopy /q /y  "Controllers\SpreadsheetHub.cs" "Excel\Controllers\" 
xcopy /q /y  "Controllers\ScheduleHub.cs" "Excel\Controllers\"
xcopy /q /y  "Helpers" "Excel\Helpers\"
xcopy /q /y  "Helpers\BrowserClasses" "Excel\Helpers\BrowserClasses\"
xcopy /q /y  "Helpers\BrowserClasses\Formatter" "Excel\Helpers\BrowserClasses\Formatter\"
xcopy  /q /y "Models\ThemeList.cs" "Excel\Models\"
xcopy  /q /y "Models\AutoFilterIconList.cs" "Excel\Models\"
xcopy /q /y  "Views" "Excel\Views\"
xcopy /q /y  "Views\Shared\_Layout.cshtml" "Excel\Views\Shared\"
xcopy /q /y  "Views\Excel" "Excel\Views\Excel\"
xcopy /q /y  "Views\Spreadsheet" "Excel\Views\Spreadsheet\"
xcopy  /q /y  "Properties" "Excel\Properties\"
xcopy  /q /y  ".gitignore" "Excel\"
xcopy  /q /y  ".gitleaksignore" "Excel\"
xcopy  /q /y  "appsettings.json" "Excel\"
xcopy  /q /y  "bundleconfig.json" "Excel\"
xcopy  /q /y  "config.json" "Excel\"
xcopy  /q /y  "gulpfile.js" "Excel\"
xcopy  /q /y  "Jenkinsfile" "Excel\" 
xcopy  /q /y  "NuGet.config" "Excel\" 
xcopy  /q /y  "package.json" "Excel\" 
xcopy  /q /y  "Program.cs" "Excel\"
xcopy  /q /y  "README.md" "Excel\" 
xcopy  /q /y  "SyncfusionLicense.txt" "Excel\" 
xcopy  /q /y  "web.config" "Excel\"
xcopy /q /y "Excel\samplelist.js" "Excel\wwwroot\scripts\"
xcopy /q /y "Excel\sampleOrder.json" "Excel\wwwroot\scripts\"
copy /y "Excel\excelHomeController.cs" "Excel\Controllers\HomeController.cs"

@echo off
set "destinationFile=Excel\Controllers\HomeController.cs"
set "searchWord=ExcelHomeController"
set "replaceWord=HomeController"

setlocal enabledelayedexpansion
(for /f "usebackq delims=" %%a in ("%destinationFile%") do (
    set "line=%%a"
    set "line=!line:%searchWord%=%replaceWord%!"
    echo !line!
)) > "%destinationFile%.tmp"

move /y "%destinationFile%.tmp" "%destinationFile%"

echo Word '%searchWord%' replaced with '%replaceWord%' in %destinationFile%