xcopy /q /y  "wwwroot\css\roboto.css" "Presentation\wwwroot\css\"
xcopy /q /y  "wwwroot\css\site.css" "Presentation\wwwroot\css\"
xcopy /q /y  "wwwroot\css\sidebar" "Presentation\wwwroot\css\sidebar\"
xcopy /q /y  "wwwroot\css\sidebar\fonts" "Presentation\wwwroot\css\sidebar\fonts\"
xcopy /q /y  "wwwroot\css\sidebar\icons" "Presentation\wwwroot\css\sidebar\icons\"
xcopy /q /y  "wwwroot\css\sidebar\icons\fonts" "Presentation\wwwroot\css\sidebar\icons\fonts\"
xcopy /q /y  "wwwroot\css\uploader" "Presentation\wwwroot\css\uploader\"
xcopy /q /y  "wwwroot\grid\adaptive-layout.css" "Presentation\wwwroot\grid\"
xcopy /q /y  "wwwroot\images\PowerPoint" "Presentation\wwwroot\images\PowerPoint\"
xcopy /q /y  "wwwroot\images\PowerPoint\CreatePresentation" "Presentation\wwwroot\images\PowerPoint\CreatePresentation\" 
xcopy /q /y  "wwwroot\lib\signalr" "Presentation\wwwroot\lib\signalr\"
xcopy /q /y  "wwwroot\PowerPoint" "Presentation\wwwroot\PowerPoint\"
xcopy /q /y  "wwwroot\scripts" "Presentation\wwwroot\scripts\"
xcopy /q /y  "wwwroot\scripts\cldr-data" "Presentation\wwwroot\scripts\cldr-data\"
xcopy /q /y  "wwwroot\scripts\cldr-data\main" "Presentation\wwwroot\scripts\cldr-data\main\"
xcopy /q /y  "wwwroot\scripts\cldr-data\main\ar\" "Presentation\wwwroot\scripts\cldr-data\main\ar\"
xcopy /q /y  "wwwroot\scripts\cldr-data\main\de\" "Presentation\wwwroot\scripts\cldr-data\main\de\"
xcopy /q /y  "wwwroot\scripts\cldr-data\main\en\" "Presentation\wwwroot\scripts\cldr-data\main\en\"
xcopy /q /y  "wwwroot\scripts\cldr-data\main\fr-CH\" "Presentation\wwwroot\scripts\cldr-data\main\fr-CH\"
xcopy /q /y  "wwwroot\scripts\cldr-data\main\he\" "Presentation\wwwroot\scripts\cldr-data\main\he\"
xcopy /q /y  "wwwroot\scripts\cldr-data\main\vi\" "Presentation\wwwroot\scripts\cldr-data\main\vi\"
xcopy /q /y  "wwwroot\scripts\cldr-data\main\zh\" "Presentation\wwwroot\scripts\cldr-data\main\zh\"
xcopy /q /y  "wwwroot\scripts\cldr-data\supplemental" "Presentation\wwwroot\scripts\cldr-data\supplemental\"
xcopy /q /y  "wwwroot\scripts\locale" "Presentation\wwwroot\scripts\locale\"
xcopy /q /y  "wwwroot\styles\file-manager" "Presentation\wwwroot\styles\file-manager\"
xcopy /q /y  "wwwroot\styles\file-manager\images" "Presentation\wwwroot\styles\file-manager\images\"
xcopy /q /y  "wwwroot\styles\images" "Presentation\wwwroot\styles\images\"
xcopy /q /y  "wwwroot\styles" "Presentation\wwwroot\styles\"
xcopy /q /y  "wwwroot\styles\images\sb-icons" "Presentation\wwwroot\styles\images\sb-icons\"
xcopy /q /y  "wwwroot\styles\images\sb-icons\fonts" "Presentation\wwwroot\styles\images\sb-icons\fonts\"
xcopy /q /y  "wwwroot" "Presentation\wwwroot\"
xcopy /q /y  "Controllers\PowerPoint" "Presentation\Controllers\PowerPoint\"
xcopy /q /y  "Controllers" "Presentation\Controllers\"
xcopy /q /y  "Helpers" "Presentation\Helpers\"
xcopy /q /y  "Helpers\BrowserClasses" "Presentation\Helpers\BrowserClasses\"
xcopy /q /y  "Helpers\BrowserClasses\Formatter" "Presentation\Helpers\BrowserClasses\Formatter\"
xcopy  /q /y  "Models\ThemeList.cs" "Presentation\Models\"
xcopy  /q /y  "Models\PresentationData.cs" "Presentation\Models\"
xcopy /q /y  "Views" "Presentation\Views\"
xcopy /q /y  "Views\Shared\_Layout.cshtml" "Presentation\Views\Shared\"
xcopy /q /y  "Views\PowerPoint" "Presentation\Views\PowerPoint\"
xcopy  /q /y  "Properties" "Presentation\Properties\"
xcopy  /q /y  ".gitignore" "Presentation\"
xcopy  /q /y  ".gitleaksignore" "Presentation\"
xcopy  /q /y  "appsettings.json" "Presentation\"
xcopy  /q /y  "bundleconfig.json" "Presentation\"
xcopy  /q /y  "config.json" "Presentation\"
xcopy  /q /y  "gulpfile.js" "Presentation\"
xcopy  /q /y  "Jenkinsfile" "Presentation\" 
xcopy  /q /y  "NuGet.config" "Presentation\" 
xcopy  /q /y  "package.json" "Presentation\" 
xcopy  /q /y  "Program.cs" "Presentation\"
xcopy  /q /y  "README.md" "Presentation\" 
xcopy  /q /y  "SyncfusionLicense.txt" "Presentation\" 
xcopy  /q /y  "web.config" "Presentation\"
xcopy /q /y  "Presentation\samplelist.js" "Presentation\wwwroot\scripts\"
xcopy /q /y "Presentation\sampleOrder.json" "Presentation\wwwroot\scripts\"
copy /y "Presentation\presentationHomeController.cs" "Presentation\Controllers\HomeController.cs"

@echo off
set "destinationFile=Presentation\Controllers\HomeController.cs"
set "searchWord=PresentationHomeController"
set "replaceWord=HomeController"

setlocal enabledelayedexpansion
(for /f "usebackq delims=" %%a in ("%destinationFile%") do (
    set "line=%%a"
    set "line=!line:%searchWord%=%replaceWord%!"
    echo !line!
)) > "%destinationFile%.tmp"

move /y "%destinationFile%.tmp" "%destinationFile%"

echo Word '%searchWord%' replaced with '%replaceWord%' in %destinationFile%