#region Copyright Syncfusion® Inc. 2001-2025.
// Copyright Syncfusion® Inc. 2001-2025. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EJ2CoreSampleBrowser.Models
{
    public class OrdersTrackData
    {
        public string OrderID { get; set; }
        public string CustomerName { get; set; }
        public string Product { get; set; }
        public string Status { get; set; }
        public DateTime OrderDate { get; set; }
        public double Amount { get; set; }

        public static List<OrdersTrackData> GetAllRecords()
        {
            return new List<OrdersTrackData>
            {
                new OrdersTrackData { OrderID = "ORD1001", CustomerName = "Eve Green", Product = "Laptop", Status = "Shipped", OrderDate =  DateTime.Parse("2025-04-25"), Amount = 148.14 },
                new OrdersTrackData { OrderID = "ORD1002", CustomerName = "Jack Black", Product = "Bag", Status = "Canceled", OrderDate =  DateTime.Parse("2025-01-17"), Amount = 39.50 },
                new OrdersTrackData { OrderID = "ORD1003", CustomerName = "David Brown", Product = "Shoe", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-15"), Amount = 206.85 },
                new OrdersTrackData { OrderID = "ORD1004", CustomerName = "Olivia Purple", Product = "Headphone", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-10-29"), Amount = 285.41 },
                new OrdersTrackData { OrderID = "ORD1005", CustomerName = "Alice Johnson", Product = "Tablet", Status = "In Transit", OrderDate =  DateTime.Parse("2025-05-23"), Amount = 163.92 },
                new OrdersTrackData { OrderID = "ORD1006", CustomerName = "Grace Lee", Product = "Bag", Status = "In Transit", OrderDate =  DateTime.Parse("2025-02-19"), Amount = 365.39 },
                new OrdersTrackData { OrderID = "ORD1007", CustomerName = "Noah Green", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-08-24"), Amount = 540.87 },
                new OrdersTrackData { OrderID = "ORD1008", CustomerName = "Henry Taylor", Product = "Shoe", Status = "Pending", OrderDate =  DateTime.Parse("2025-11-18"), Amount = 622.33 },
                new OrdersTrackData { OrderID = "ORD1009", CustomerName = "Kelly Gray", Product = "Headphone", Status = "Pending", OrderDate =  DateTime.Parse("2025-01-24"), Amount = 664.65 },
                new OrdersTrackData { OrderID = "ORD1010", CustomerName = "Henry Taylor", Product = "Headphone", Status = "Pending", OrderDate =  DateTime.Parse("2025-07-14"), Amount = 285.19 },
                new OrdersTrackData { OrderID = "ORD1011", CustomerName = "Alice Johnson", Product = "Phone", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-04-18"), Amount = 673.47 },
                new OrdersTrackData { OrderID = "ORD1012", CustomerName = "Noah Green", Product = "Watch", Status = "Canceled", OrderDate =  DateTime.Parse("2025-03-25"), Amount = 467.64 },
                new OrdersTrackData { OrderID = "ORD1013", CustomerName = "Jack Black", Product = "Headphone", Status = "In Transit", OrderDate =  DateTime.Parse("2025-01-29"), Amount = 236.76 },
                new OrdersTrackData { OrderID = "ORD1014", CustomerName = "Mia Blue", Product = "Tablet", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-02-03"), Amount = 218.87 },
                new OrdersTrackData { OrderID = "ORD1015", CustomerName = "Carol Davis", Product = "Camera", Status = "Delivered", OrderDate =  DateTime.Parse("2025-11-26"), Amount = 464.26 },
                new OrdersTrackData { OrderID = "ORD1016", CustomerName = "Frank Miller", Product = "Headphone", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-10-27"), Amount = 434.15 },
                new OrdersTrackData { OrderID = "ORD1017", CustomerName = "Rose Pink", Product = "Headphone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-09-18"), Amount = 498.58 },
                new OrdersTrackData { OrderID = "ORD1018", CustomerName = "Grace Lee", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-12-15"), Amount = 427.94 },
                new OrdersTrackData { OrderID = "ORD1019", CustomerName = "Quinn Yellow", Product = "Tablet", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-09-28"), Amount = 258.90 },
                new OrdersTrackData { OrderID = "ORD1020", CustomerName = "Grace Lee", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-11-25"), Amount = 346.77 },
                new OrdersTrackData { OrderID = "ORD1021", CustomerName = "Olivia Purple", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-01-02"), Amount = 954.28 },
                new OrdersTrackData { OrderID = "ORD1022", CustomerName = "Ivy White", Product = "Watch", Status = "Pending", OrderDate =  DateTime.Parse("2025-11-17"), Amount = 305.46 },
                new OrdersTrackData { OrderID = "ORD1023", CustomerName = "Noah Green", Product = "Headphone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-07-11"), Amount = 764.89 },
                new OrdersTrackData { OrderID = "ORD1024", CustomerName = "Ivy White", Product = "Shirt", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-09-08"), Amount = 29.28 },
                new OrdersTrackData { OrderID = "ORD1025", CustomerName = "Bob Wilson", Product = "Headphone", Status = "Pending", OrderDate =  DateTime.Parse("2025-05-04"), Amount = 879.23 },
                new OrdersTrackData { OrderID = "ORD1026", CustomerName = "Henry Taylor", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-09-30"), Amount = 768.18 },
                new OrdersTrackData { OrderID = "ORD1027", CustomerName = "Paul Orange", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-05-16"), Amount = 532.40 },
                new OrdersTrackData { OrderID = "ORD1028", CustomerName = "Carol Davis", Product = "Shoe", Status = "Canceled", OrderDate =  DateTime.Parse("2025-06-09"), Amount = 405.00 },
                new OrdersTrackData { OrderID = "ORD1029", CustomerName = "Leo Red", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-03-03"), Amount = 255.43 },
                new OrdersTrackData { OrderID = "ORD1030", CustomerName = "Mia Blue", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-10-29"), Amount = 228.02 },
                new OrdersTrackData { OrderID = "ORD1031", CustomerName = "Jane Smith", Product = "Headphone", Status = "Pending", OrderDate =  DateTime.Parse("2025-01-17"), Amount = 861.04 },
                new OrdersTrackData { OrderID = "ORD1032", CustomerName = "Ivy White", Product = "Headphone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-12-09"), Amount = 490.56 },
                new OrdersTrackData { OrderID = "ORD1033", CustomerName = "Frank Miller", Product = "Book", Status = "Canceled", OrderDate =  DateTime.Parse("2025-05-05"), Amount = 786.77 },
                new OrdersTrackData { OrderID = "ORD1034", CustomerName = "Carol Davis", Product = "Bag", Status = "Pending", OrderDate =  DateTime.Parse("2025-12-04"), Amount = 436.74 },
                new OrdersTrackData { OrderID = "ORD1035", CustomerName = "Olivia Purple", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-12-11"), Amount = 656.92 },
                new OrdersTrackData { OrderID = "ORD1036", CustomerName = "Jane Smith", Product = "Tablet", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-02-25"), Amount = 256.17 },
                new OrdersTrackData { OrderID = "ORD1037", CustomerName = "Jack Black", Product = "Camera", Status = "Shipped", OrderDate =  DateTime.Parse("2025-08-05"), Amount = 191.65 },
                new OrdersTrackData { OrderID = "ORD1038", CustomerName = "David Brown", Product = "Bag", Status = "Shipped", OrderDate =  DateTime.Parse("2025-10-09"), Amount = 106.93 },
                new OrdersTrackData { OrderID = "ORD1039", CustomerName = "Eve Green", Product = "Bag", Status = "Shipped", OrderDate =  DateTime.Parse("2025-03-27"), Amount = 412.35 },
                new OrdersTrackData { OrderID = "ORD1040", CustomerName = "Carol Davis", Product = "Tablet", Status = "Pending", OrderDate =  DateTime.Parse("2025-03-26"), Amount = 385.18 },
                new OrdersTrackData { OrderID = "ORD1041", CustomerName = "John Doe", Product = "Camera", Status = "In Transit", OrderDate =  DateTime.Parse("2025-08-05"), Amount = 699.63 },
                new OrdersTrackData { OrderID = "ORD1042", CustomerName = "Frank Miller", Product = "Headphone", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-04-22"), Amount = 969.02 },
                new OrdersTrackData { OrderID = "ORD1043", CustomerName = "Jane Smith", Product = "Phone", Status = "Pending", OrderDate =  DateTime.Parse("2025-01-26"), Amount = 588.34 },
                new OrdersTrackData { OrderID = "ORD1044", CustomerName = "Ivy White", Product = "Watch", Status = "Pending", OrderDate =  DateTime.Parse("2025-09-18"), Amount = 89.31 },
                new OrdersTrackData { OrderID = "ORD1045", CustomerName = "Henry Taylor", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-12-12"), Amount = 863.20 },
                new OrdersTrackData { OrderID = "ORD1046", CustomerName = "Grace Lee", Product = "Book", Status = "Shipped", OrderDate =  DateTime.Parse("2025-10-24"), Amount = 598.57 },
                new OrdersTrackData { OrderID = "ORD1047", CustomerName = "Olivia Purple", Product = "Book", Status = "In Transit", OrderDate =  DateTime.Parse("2025-05-14"), Amount = 212.22 },
                new OrdersTrackData { OrderID = "ORD1048", CustomerName = "David Brown", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-03-09"), Amount = 674.97 },
                new OrdersTrackData { OrderID = "ORD1049", CustomerName = "Leo Red", Product = "Phone", Status = "Pending", OrderDate =  DateTime.Parse("2025-01-05"), Amount = 463.70 },
                new OrdersTrackData { OrderID = "ORD1050", CustomerName = "Henry Taylor", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-09-17"), Amount = 272.55 },
                new OrdersTrackData { OrderID = "ORD1051", CustomerName = "Henry Taylor", Product = "Headphone", Status = "Pending", OrderDate =  DateTime.Parse("2025-05-26"), Amount = 166.17 },
                new OrdersTrackData { OrderID = "ORD1052", CustomerName = "Bob Wilson", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-12-08"), Amount = 818.93 },
                new OrdersTrackData { OrderID = "ORD1053", CustomerName = "Grace Lee", Product = "Watch", Status = "In Transit", OrderDate =  DateTime.Parse("2025-03-01"), Amount = 890.82 },
                new OrdersTrackData { OrderID = "ORD1054", CustomerName = "John Doe", Product = "Laptop", Status = "Shipped", OrderDate =  DateTime.Parse("2025-06-25"), Amount = 211.56 },
                new OrdersTrackData { OrderID = "ORD1055", CustomerName = "Ivy White", Product = "Camera", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-01-27"), Amount = 101.38 },
                new OrdersTrackData { OrderID = "ORD1056", CustomerName = "John Doe", Product = "Shirt", Status = "Pending", OrderDate =  DateTime.Parse("2025-06-20"), Amount = 773.41 },
                new OrdersTrackData { OrderID = "ORD1057", CustomerName = "Alice Johnson", Product = "Camera", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-10-15"), Amount = 19.57 },
                new OrdersTrackData { OrderID = "ORD1058", CustomerName = "Frank Miller", Product = "Shoe", Status = "Pending", OrderDate =  DateTime.Parse("2025-07-09"), Amount = 586.68 },
                new OrdersTrackData { OrderID = "ORD1059", CustomerName = "Olivia Purple", Product = "Watch", Status = "Pending", OrderDate =  DateTime.Parse("2025-06-07"), Amount = 371.01 },
                new OrdersTrackData { OrderID = "ORD1060", CustomerName = "Rose Pink", Product = "Headphone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-12-08"), Amount = 111.77 },
                new OrdersTrackData { OrderID = "ORD1061", CustomerName = "Noah Green", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-03-25"), Amount = 976.44 },
                new OrdersTrackData { OrderID = "ORD1062", CustomerName = "Olivia Purple", Product = "Shirt", Status = "Delivered", OrderDate =  DateTime.Parse("2025-06-20"), Amount = 784.56 },
                new OrdersTrackData { OrderID = "ORD1063", CustomerName = "David Brown", Product = "Laptop", Status = "Canceled", OrderDate =  DateTime.Parse("2025-12-26"), Amount = 117.01 },
                new OrdersTrackData { OrderID = "ORD1064", CustomerName = "Paul Orange", Product = "Headphone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-08-24"), Amount = 356.16 },
                new OrdersTrackData { OrderID = "ORD1065", CustomerName = "David Brown", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-07-24"), Amount = 334.98 },
                new OrdersTrackData { OrderID = "ORD1066", CustomerName = "John Doe", Product = "Phone", Status = "In Transit", OrderDate =  DateTime.Parse("2025-12-14"), Amount = 981.34 },
                new OrdersTrackData { OrderID = "ORD1067", CustomerName = "Mia Blue", Product = "Shirt", Status = "Pending", OrderDate =  DateTime.Parse("2025-05-14"), Amount = 186.78 },
                new OrdersTrackData { OrderID = "ORD1068", CustomerName = "Jane Smith", Product = "Bag", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-06-26"), Amount = 731.26 },
                new OrdersTrackData { OrderID = "ORD1069", CustomerName = "Olivia Purple", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-07-17"), Amount = 900.51 },
                new OrdersTrackData { OrderID = "ORD1070", CustomerName = "John Doe", Product = "Shirt", Status = "Delivered", OrderDate =  DateTime.Parse("2025-01-01"), Amount = 524.72 },
                new OrdersTrackData { OrderID = "ORD1071", CustomerName = "Carol Davis", Product = "Phone", Status = "Delivered", OrderDate =  DateTime.Parse("2025-02-05"), Amount = 949.39 },
                new OrdersTrackData { OrderID = "ORD1072", CustomerName = "Noah Green", Product = "Phone", Status = "Pending", OrderDate =  DateTime.Parse("2025-06-03"), Amount = 512.05 },
                new OrdersTrackData { OrderID = "ORD1073", CustomerName = "Mia Blue", Product = "Tablet", Status = "In Transit", OrderDate =  DateTime.Parse("2025-10-11"), Amount = 136.01 },
                new OrdersTrackData { OrderID = "ORD1074", CustomerName = "Quinn Yellow", Product = "Watch", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-07-27"), Amount = 552.46 },
                new OrdersTrackData { OrderID = "ORD1075", CustomerName = "Bob Wilson", Product = "Laptop", Status = "Shipped", OrderDate =  DateTime.Parse("2025-08-09"), Amount = 787.90 },
                new OrdersTrackData { OrderID = "ORD1076", CustomerName = "Leo Red", Product = "Camera", Status = "In Transit", OrderDate =  DateTime.Parse("2025-12-12"), Amount = 221.56 },
                new OrdersTrackData { OrderID = "ORD1077", CustomerName = "Alice Johnson", Product = "Bag", Status = "Pending", OrderDate =  DateTime.Parse("2025-09-21"), Amount = 667.22 },
                new OrdersTrackData { OrderID = "ORD1078", CustomerName = "Henry Taylor", Product = "Headphone", Status = "Canceled", OrderDate =  DateTime.Parse("2025-04-26"), Amount = 808.50 },
                new OrdersTrackData { OrderID = "ORD1079", CustomerName = "Eve Green", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-09-01"), Amount = 615.16 },
                new OrdersTrackData { OrderID = "ORD1080", CustomerName = "Leo Red", Product = "Tablet", Status = "Shipped", OrderDate =  DateTime.Parse("2025-12-23"), Amount = 390.14 },
                new OrdersTrackData { OrderID = "ORD1081", CustomerName = "David Brown", Product = "Watch", Status = "Pending", OrderDate =  DateTime.Parse("2025-02-24"), Amount = 780.64 },
                new OrdersTrackData { OrderID = "ORD1082", CustomerName = "Alice Johnson", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-01-26"), Amount = 561.83 },
                new OrdersTrackData { OrderID = "ORD1083", CustomerName = "Leo Red", Product = "Watch", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-12-08"), Amount = 535.82 },
                new OrdersTrackData { OrderID = "ORD1084", CustomerName = "Leo Red", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-08"), Amount = 451.45 },
                new OrdersTrackData { OrderID = "ORD1085", CustomerName = "Paul Orange", Product = "Camera", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-05-07"), Amount = 841.46 },
                new OrdersTrackData { OrderID = "ORD1086", CustomerName = "Ivy White", Product = "Camera", Status = "Shipped", OrderDate =  DateTime.Parse("2025-05-21"), Amount = 445.47 },
                new OrdersTrackData { OrderID = "ORD1087", CustomerName = "David Brown", Product = "Laptop", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-06-13"), Amount = 894.10 },
                new OrdersTrackData { OrderID = "ORD1088", CustomerName = "Frank Miller", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-07-16"), Amount = 697.01 },
                new OrdersTrackData { OrderID = "ORD1089", CustomerName = "Henry Taylor", Product = "Tablet", Status = "Pending", OrderDate =  DateTime.Parse("2025-06-19"), Amount = 547.19 },
                new OrdersTrackData { OrderID = "ORD1090", CustomerName = "Jane Smith", Product = "Headphone", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-07-19"), Amount = 905.79 },
                new OrdersTrackData { OrderID = "ORD1091", CustomerName = "Kelly Gray", Product = "Tablet", Status = "Pending", OrderDate =  DateTime.Parse("2025-01-04"), Amount = 943.31 },
                new OrdersTrackData { OrderID = "ORD1092", CustomerName = "Quinn Yellow", Product = "Tablet", Status = "Shipped", OrderDate =  DateTime.Parse("2025-09-07"), Amount = 227.23 },
                new OrdersTrackData { OrderID = "ORD1093", CustomerName = "Paul Orange", Product = "Shirt", Status = "In Transit", OrderDate =  DateTime.Parse("2025-06-22"), Amount = 672.18 },
                new OrdersTrackData { OrderID = "ORD1094", CustomerName = "Alice Johnson", Product = "Camera", Status = "Shipped", OrderDate =  DateTime.Parse("2025-11-15"), Amount = 538.78 },
                new OrdersTrackData { OrderID = "ORD1095", CustomerName = "Kelly Gray", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-02-12"), Amount = 646.32 },
                new OrdersTrackData { OrderID = "ORD1096", CustomerName = "Leo Red", Product = "Watch", Status = "Pending", OrderDate =  DateTime.Parse("2025-05-14"), Amount = 385.31 },
                new OrdersTrackData { OrderID = "ORD1097", CustomerName = "Leo Red", Product = "Phone", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-07-14"), Amount = 285.47 },
                new OrdersTrackData { OrderID = "ORD1098", CustomerName = "John Doe", Product = "Bag", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-01-10"), Amount = 751.53 },
                new OrdersTrackData { OrderID = "ORD1099", CustomerName = "Rose Pink", Product = "Headphone", Status = "Pending", OrderDate =  DateTime.Parse("2025-11-30"), Amount = 49.86 },
                new OrdersTrackData { OrderID = "ORD1100", CustomerName = "David Brown", Product = "Headphone", Status = "Pending", OrderDate =  DateTime.Parse("2025-11-15"), Amount = 160.86 },
                new OrdersTrackData { OrderID = "ORD1101", CustomerName = "Paul Orange", Product = "Bag", Status = "Shipped", OrderDate =  DateTime.Parse("2025-08-27"), Amount = 702.47 },
                new OrdersTrackData { OrderID = "ORD1102", CustomerName = "Alice Johnson", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-03-25"), Amount = 965.07 },
                new OrdersTrackData { OrderID = "ORD1103", CustomerName = "Kelly Gray", Product = "Shirt", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-10-22"), Amount = 680.57 },
                new OrdersTrackData { OrderID = "ORD1104", CustomerName = "Quinn Yellow", Product = "Headphone", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-31"), Amount = 693.71 },
                new OrdersTrackData { OrderID = "ORD1105", CustomerName = "Grace Lee", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-17"), Amount = 784.81 },
                new OrdersTrackData { OrderID = "ORD1106", CustomerName = "Jack Black", Product = "Tablet", Status = "Shipped", OrderDate =  DateTime.Parse("2025-02-05"), Amount = 510.90 },
                new OrdersTrackData { OrderID = "ORD1107", CustomerName = "Eve Green", Product = "Tablet", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-02-24"), Amount = 439.19 },
                new OrdersTrackData { OrderID = "ORD1108", CustomerName = "Leo Red", Product = "Watch", Status = "In Transit", OrderDate =  DateTime.Parse("2025-04-01"), Amount = 736.46 },
                new OrdersTrackData { OrderID = "ORD1109", CustomerName = "Noah Green", Product = "Shoe", Status = "In Transit", OrderDate =  DateTime.Parse("2025-08-27"), Amount = 441.22 },
                new OrdersTrackData { OrderID = "ORD1110", CustomerName = "Mia Blue", Product = "Headphone", Status = "Pending", OrderDate =  DateTime.Parse("2025-05-23"), Amount = 882.81 },
                new OrdersTrackData { OrderID = "ORD1111", CustomerName = "Leo Red", Product = "Book", Status = "Shipped", OrderDate =  DateTime.Parse("2025-06-22"), Amount = 38.41 },
                new OrdersTrackData { OrderID = "ORD1112", CustomerName = "Alice Johnson", Product = "Camera", Status = "Shipped", OrderDate =  DateTime.Parse("2025-07-01"), Amount = 799.85 },
                new OrdersTrackData { OrderID = "ORD1113", CustomerName = "John Doe", Product = "Book", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-10-12"), Amount = 20.05 },
                new OrdersTrackData { OrderID = "ORD1114", CustomerName = "Henry Taylor", Product = "Headphone", Status = "Delivered", OrderDate =  DateTime.Parse("2025-09-08"), Amount = 559.62 },
                new OrdersTrackData { OrderID = "ORD1115", CustomerName = "Paul Orange", Product = "Camera", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-01-09"), Amount = 102.12 },
                new OrdersTrackData { OrderID = "ORD1116", CustomerName = "Quinn Yellow", Product = "Headphone", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-12-06"), Amount = 585.74 },
                new OrdersTrackData { OrderID = "ORD1117", CustomerName = "Jack Black", Product = "Shoe", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-08-06"), Amount = 996.67 },
                new OrdersTrackData { OrderID = "ORD1118", CustomerName = "Rose Pink", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-06-06"), Amount = 258.89 },
                new OrdersTrackData { OrderID = "ORD1119", CustomerName = "Carol Davis", Product = "Phone", Status = "Canceled", OrderDate =  DateTime.Parse("2025-10-02"), Amount = 951.37 },
                new OrdersTrackData { OrderID = "ORD1120", CustomerName = "Carol Davis", Product = "Headphone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-05-22"), Amount = 727.34 },
                new OrdersTrackData { OrderID = "ORD1121", CustomerName = "Noah Green", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-04-10"), Amount = 303.28 },
                new OrdersTrackData { OrderID = "ORD1122", CustomerName = "Alice Johnson", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-12-29"), Amount = 538.79 },
                new OrdersTrackData { OrderID = "ORD1123", CustomerName = "Jane Smith", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-12-24"), Amount = 944.65 },
                new OrdersTrackData { OrderID = "ORD1124", CustomerName = "Grace Lee", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-08-29"), Amount = 483.93 },
                new OrdersTrackData { OrderID = "ORD1125", CustomerName = "Alice Johnson", Product = "Shirt", Status = "In Transit", OrderDate =  DateTime.Parse("2025-09-02"), Amount = 122.95 },
                new OrdersTrackData { OrderID = "ORD1126", CustomerName = "Quinn Yellow", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-23"), Amount = 633.15 },
                new OrdersTrackData { OrderID = "ORD1127", CustomerName = "Frank Miller", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-02-13"), Amount = 993.98 },
                new OrdersTrackData { OrderID = "ORD1128", CustomerName = "Jack Black", Product = "Tablet", Status = "Shipped", OrderDate =  DateTime.Parse("2025-09-25"), Amount = 386.57 },
                new OrdersTrackData { OrderID = "ORD1129", CustomerName = "Bob Wilson", Product = "Book", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-06-06"), Amount = 572.94 },
                new OrdersTrackData { OrderID = "ORD1130", CustomerName = "Noah Green", Product = "Bag", Status = "Shipped", OrderDate =  DateTime.Parse("2025-11-17"), Amount = 218.91 },
                new OrdersTrackData { OrderID = "ORD1131", CustomerName = "Alice Johnson", Product = "Headphone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-10-10"), Amount = 84.31 },
                new OrdersTrackData { OrderID = "ORD1132", CustomerName = "Olivia Purple", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-05-30"), Amount = 42.31 },
                new OrdersTrackData { OrderID = "ORD1133", CustomerName = "Bob Wilson", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-12-18"), Amount = 241.09 },
                new OrdersTrackData { OrderID = "ORD1134", CustomerName = "Kelly Gray", Product = "Headphone", Status = "Delivered", OrderDate =  DateTime.Parse("2025-02-28"), Amount = 549.12 },
                new OrdersTrackData { OrderID = "ORD1135", CustomerName = "John Doe", Product = "Watch", Status = "Pending", OrderDate =  DateTime.Parse("2025-01-31"), Amount = 174.26 },
                new OrdersTrackData { OrderID = "ORD1136", CustomerName = "Noah Green", Product = "Book", Status = "In Transit", OrderDate =  DateTime.Parse("2025-08-13"), Amount = 133.11 },
                new OrdersTrackData { OrderID = "ORD1137", CustomerName = "Quinn Yellow", Product = "Laptop", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-08-13"), Amount = 89.64 },
                new OrdersTrackData { OrderID = "ORD1138", CustomerName = "Olivia Purple", Product = "Phone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-01-14"), Amount = 100.41 },
                new OrdersTrackData { OrderID = "ORD1139", CustomerName = "John Doe", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-03-31"), Amount = 475.80 },
                new OrdersTrackData { OrderID = "ORD1140", CustomerName = "John Doe", Product = "Watch", Status = "Canceled", OrderDate =  DateTime.Parse("2025-11-22"), Amount = 816.10 },
                new OrdersTrackData { OrderID = "ORD1141", CustomerName = "Paul Orange", Product = "Phone", Status = "Delivered", OrderDate =  DateTime.Parse("2025-06-20"), Amount = 327.85 },
                new OrdersTrackData { OrderID = "ORD1142", CustomerName = "Alice Johnson", Product = "Phone", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-12-22"), Amount = 500.51 },
                new OrdersTrackData { OrderID = "ORD1143", CustomerName = "Jack Black", Product = "Shirt", Status = "In Transit", OrderDate =  DateTime.Parse("2025-02-15"), Amount = 321.37 },
                new OrdersTrackData { OrderID = "ORD1144", CustomerName = "Grace Lee", Product = "Tablet", Status = "Pending", OrderDate =  DateTime.Parse("2025-12-03"), Amount = 870.67 },
                new OrdersTrackData { OrderID = "ORD1145", CustomerName = "Olivia Purple", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-09-23"), Amount = 368.16 },
                new OrdersTrackData { OrderID = "ORD1146", CustomerName = "Leo Red", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-05-17"), Amount = 553.73 },
                new OrdersTrackData { OrderID = "ORD1147", CustomerName = "Leo Red", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-01-15"), Amount = 973.42 },
                new OrdersTrackData { OrderID = "ORD1148", CustomerName = "Alice Johnson", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-10"), Amount = 413.91 },
                new OrdersTrackData { OrderID = "ORD1149", CustomerName = "Grace Lee", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-11-28"), Amount = 833.82 },
                new OrdersTrackData { OrderID = "ORD1150", CustomerName = "Bob Wilson", Product = "Shoe", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-08-01"), Amount = 836.38 },
                new OrdersTrackData { OrderID = "ORD1151", CustomerName = "David Brown", Product = "Camera", Status = "Shipped", OrderDate =  DateTime.Parse("2025-07-16"), Amount = 198.70 },
                new OrdersTrackData { OrderID = "ORD1152", CustomerName = "Frank Miller", Product = "Bag", Status = "Canceled", OrderDate =  DateTime.Parse("2025-08-01"), Amount = 346.48 },
                new OrdersTrackData { OrderID = "ORD1153", CustomerName = "John Doe", Product = "Shirt", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-06-02"), Amount = 839.10 },
                new OrdersTrackData { OrderID = "ORD1154", CustomerName = "Frank Miller", Product = "Camera", Status = "Shipped", OrderDate =  DateTime.Parse("2025-06-26"), Amount = 339.12 },
                new OrdersTrackData { OrderID = "ORD1155", CustomerName = "Quinn Yellow", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-04-07"), Amount = 980.97 },
                new OrdersTrackData { OrderID = "ORD1156", CustomerName = "Kelly Gray", Product = "Tablet", Status = "Shipped", OrderDate =  DateTime.Parse("2025-07-30"), Amount = 53.21 },
                new OrdersTrackData { OrderID = "ORD1157", CustomerName = "Quinn Yellow", Product = "Tablet", Status = "Delivered", OrderDate =  DateTime.Parse("2025-09-11"), Amount = 965.18 },
                new OrdersTrackData { OrderID = "ORD1158", CustomerName = "Ivy White", Product = "Book", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-02-21"), Amount = 875.45 },
                new OrdersTrackData { OrderID = "ORD1159", CustomerName = "Grace Lee", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-01-08"), Amount = 725.22 },
                new OrdersTrackData { OrderID = "ORD1160", CustomerName = "Frank Miller", Product = "Bag", Status = "In Transit", OrderDate =  DateTime.Parse("2025-05-16"), Amount = 345.18 },
                new OrdersTrackData { OrderID = "ORD1161", CustomerName = "Henry Taylor", Product = "Phone", Status = "In Transit", OrderDate =  DateTime.Parse("2025-06-12"), Amount = 630.53 },
                new OrdersTrackData { OrderID = "ORD1162", CustomerName = "Jack Black", Product = "Shirt", Status = "Pending", OrderDate =  DateTime.Parse("2025-05-01"), Amount = 634.85 },
                new OrdersTrackData { OrderID = "ORD1163", CustomerName = "David Brown", Product = "Bag", Status = "Canceled", OrderDate =  DateTime.Parse("2025-02-20"), Amount = 762.77 },
                new OrdersTrackData { OrderID = "ORD1164", CustomerName = "Leo Red", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-01-15"), Amount = 55.53 },
                new OrdersTrackData { OrderID = "ORD1165", CustomerName = "Bob Wilson", Product = "Phone", Status = "Pending", OrderDate =  DateTime.Parse("2025-08-09"), Amount = 154.11 },
                new OrdersTrackData { OrderID = "ORD1166", CustomerName = "Olivia Purple", Product = "Book", Status = "Shipped", OrderDate =  DateTime.Parse("2025-03-29"), Amount = 183.32 },
                new OrdersTrackData { OrderID = "ORD1167", CustomerName = "Noah Green", Product = "Headphone", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-26"), Amount = 151.69 },
                new OrdersTrackData { OrderID = "ORD1168", CustomerName = "John Doe", Product = "Camera", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-12-08"), Amount = 19.30 },
                new OrdersTrackData { OrderID = "ORD1169", CustomerName = "Bob Wilson", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-02-07"), Amount = 447.31 },
                new OrdersTrackData { OrderID = "ORD1170", CustomerName = "Kelly Gray", Product = "Laptop", Status = "Canceled", OrderDate =  DateTime.Parse("2025-12-20"), Amount = 257.60 },
                new OrdersTrackData { OrderID = "ORD1171", CustomerName = "Carol Davis", Product = "Tablet", Status = "In Transit", OrderDate =  DateTime.Parse("2025-02-24"), Amount = 244.83 },
                new OrdersTrackData { OrderID = "ORD1172", CustomerName = "Kelly Gray", Product = "Laptop", Status = "In Transit", OrderDate =  DateTime.Parse("2025-01-12"), Amount = 978.17 },
                new OrdersTrackData { OrderID = "ORD1173", CustomerName = "John Doe", Product = "Shirt", Status = "Pending", OrderDate =  DateTime.Parse("2025-11-07"), Amount = 747.72 },
                new OrdersTrackData { OrderID = "ORD1174", CustomerName = "David Brown", Product = "Book", Status = "Shipped", OrderDate =  DateTime.Parse("2025-04-23"), Amount = 640.25 },
                new OrdersTrackData { OrderID = "ORD1175", CustomerName = "Frank Miller", Product = "Bag", Status = "Pending", OrderDate =  DateTime.Parse("2025-06-08"), Amount = 790.72 },
                new OrdersTrackData { OrderID = "ORD1176", CustomerName = "Kelly Gray", Product = "Phone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-02-16"), Amount = 910.53 },
                new OrdersTrackData { OrderID = "ORD1177", CustomerName = "Olivia Purple", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-03-09"), Amount = 788.65 },
                new OrdersTrackData { OrderID = "ORD1178", CustomerName = "Ivy White", Product = "Shoe", Status = "Pending", OrderDate =  DateTime.Parse("2025-03-26"), Amount = 264.40 },
                new OrdersTrackData { OrderID = "ORD1179", CustomerName = "Bob Wilson", Product = "Phone", Status = "Pending", OrderDate =  DateTime.Parse("2025-08-28"), Amount = 963.26 },
                new OrdersTrackData { OrderID = "ORD1180", CustomerName = "David Brown", Product = "Tablet", Status = "Canceled", OrderDate =  DateTime.Parse("2025-02-16"), Amount = 792.78 },
                new OrdersTrackData { OrderID = "ORD1181", CustomerName = "John Doe", Product = "Shoe", Status = "Pending", OrderDate =  DateTime.Parse("2025-08-21"), Amount = 374.90 },
                new OrdersTrackData { OrderID = "ORD1182", CustomerName = "Kelly Gray", Product = "Tablet", Status = "Canceled", OrderDate =  DateTime.Parse("2025-02-25"), Amount = 678.09 },
                new OrdersTrackData { OrderID = "ORD1183", CustomerName = "Eve Green", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-11-09"), Amount = 229.15 },
                new OrdersTrackData { OrderID = "ORD1184", CustomerName = "Leo Red", Product = "Laptop", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-03-01"), Amount = 148.38 },
                new OrdersTrackData { OrderID = "ORD1185", CustomerName = "Bob Wilson", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-02-19"), Amount = 242.45 },
                new OrdersTrackData { OrderID = "ORD1186", CustomerName = "Olivia Purple", Product = "Book", Status = "Shipped", OrderDate =  DateTime.Parse("2025-08-01"), Amount = 658.37 },
                new OrdersTrackData { OrderID = "ORD1187", CustomerName = "Noah Green", Product = "Tablet", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-01-17"), Amount = 693.38 },
                new OrdersTrackData { OrderID = "ORD1188", CustomerName = "Leo Red", Product = "Camera", Status = "Shipped", OrderDate =  DateTime.Parse("2025-07-05"), Amount = 108.36 },
                new OrdersTrackData { OrderID = "ORD1189", CustomerName = "Jack Black", Product = "Phone", Status = "Pending", OrderDate =  DateTime.Parse("2025-07-23"), Amount = 283.12 },
                new OrdersTrackData { OrderID = "ORD1190", CustomerName = "Leo Red", Product = "Bag", Status = "Shipped", OrderDate =  DateTime.Parse("2025-11-25"), Amount = 643.10 },
                new OrdersTrackData { OrderID = "ORD1191", CustomerName = "Jane Smith", Product = "Phone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-03-06"), Amount = 789.11 },
                new OrdersTrackData { OrderID = "ORD1192", CustomerName = "Henry Taylor", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-10-28"), Amount = 223.79 },
                new OrdersTrackData { OrderID = "ORD1193", CustomerName = "Mia Blue", Product = "Watch", Status = "Pending", OrderDate =  DateTime.Parse("2025-05-22"), Amount = 859.82 },
                new OrdersTrackData { OrderID = "ORD1194", CustomerName = "Frank Miller", Product = "Shoe", Status = "Pending", OrderDate =  DateTime.Parse("2025-03-31"), Amount = 118.83 },
                new OrdersTrackData { OrderID = "ORD1195", CustomerName = "Frank Miller", Product = "Shirt", Status = "Pending", OrderDate =  DateTime.Parse("2025-05-02"), Amount = 592.96 },
                new OrdersTrackData { OrderID = "ORD1196", CustomerName = "Alice Johnson", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-03-06"), Amount = 744.30 },
                new OrdersTrackData { OrderID = "ORD1197", CustomerName = "Grace Lee", Product = "Bag", Status = "Pending", OrderDate =  DateTime.Parse("2025-08-18"), Amount = 780.24 },
                new OrdersTrackData { OrderID = "ORD1198", CustomerName = "Kelly Gray", Product = "Bag", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-09-15"), Amount = 229.33 },
                new OrdersTrackData { OrderID = "ORD1199", CustomerName = "Ivy White", Product = "Laptop", Status = "Shipped", OrderDate =  DateTime.Parse("2025-11-26"), Amount = 964.39 },
                new OrdersTrackData { OrderID = "ORD1200", CustomerName = "Paul Orange", Product = "Tablet", Status = "In Transit", OrderDate =  DateTime.Parse("2025-12-18"), Amount = 116.88 },
                new OrdersTrackData { OrderID = "ORD1201", CustomerName = "Henry Taylor", Product = "Bag", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-11-08"), Amount = 156.85 },
                new OrdersTrackData { OrderID = "ORD1202", CustomerName = "John Doe", Product = "Book", Status = "Delivered", OrderDate =  DateTime.Parse("2025-07-15"), Amount = 994.68 },
                new OrdersTrackData { OrderID = "ORD1203", CustomerName = "Bob Wilson", Product = "Camera", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-02-20"), Amount = 795.17 },
                new OrdersTrackData { OrderID = "ORD1204", CustomerName = "Jack Black", Product = "Headphone", Status = "In Transit", OrderDate =  DateTime.Parse("2025-08-20"), Amount = 889.21 },
                new OrdersTrackData { OrderID = "ORD1205", CustomerName = "Mia Blue", Product = "Camera", Status = "In Transit", OrderDate =  DateTime.Parse("2025-08-01"), Amount = 732.32 },
                new OrdersTrackData { OrderID = "ORD1206", CustomerName = "Olivia Purple", Product = "Phone", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-07-11"), Amount = 954.06 },
                new OrdersTrackData { OrderID = "ORD1207", CustomerName = "Henry Taylor", Product = "Bag", Status = "Pending", OrderDate =  DateTime.Parse("2025-02-17"), Amount = 437.56 },
                new OrdersTrackData { OrderID = "ORD1208", CustomerName = "Frank Miller", Product = "Shoe", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-28"), Amount = 957.06 },
                new OrdersTrackData { OrderID = "ORD1209", CustomerName = "Grace Lee", Product = "Tablet", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-12-07"), Amount = 941.72 },
                new OrdersTrackData { OrderID = "ORD1210", CustomerName = "Jane Smith", Product = "Laptop", Status = "In Transit", OrderDate =  DateTime.Parse("2025-06-30"), Amount = 112.56 },
                new OrdersTrackData { OrderID = "ORD1211", CustomerName = "Carol Davis", Product = "Watch", Status = "Canceled", OrderDate =  DateTime.Parse("2025-04-25"), Amount = 848.80 },
                new OrdersTrackData { OrderID = "ORD1212", CustomerName = "Jack Black", Product = "Phone", Status = "Pending", OrderDate =  DateTime.Parse("2025-05-23"), Amount = 578.36 },
                new OrdersTrackData { OrderID = "ORD1213", CustomerName = "Jack Black", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-11-08"), Amount = 929.79 },
                new OrdersTrackData { OrderID = "ORD1214", CustomerName = "Eve Green", Product = "Watch", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-12-26"), Amount = 764.79 },
                new OrdersTrackData { OrderID = "ORD1215", CustomerName = "Rose Pink", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-03-15"), Amount = 570.66 },
                new OrdersTrackData { OrderID = "ORD1216", CustomerName = "Henry Taylor", Product = "Watch", Status = "Pending", OrderDate =  DateTime.Parse("2025-02-16"), Amount = 748.65 },
                new OrdersTrackData { OrderID = "ORD1217", CustomerName = "Quinn Yellow", Product = "Tablet", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-06-24"), Amount = 165.84 },
                new OrdersTrackData { OrderID = "ORD1218", CustomerName = "Mia Blue", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-01-27"), Amount = 164.02 },
                new OrdersTrackData { OrderID = "ORD1219", CustomerName = "Henry Taylor", Product = "Laptop", Status = "Delivered", OrderDate =  DateTime.Parse("2025-12-05"), Amount = 429.77 },
                new OrdersTrackData { OrderID = "ORD1220", CustomerName = "Olivia Purple", Product = "Laptop", Status = "Shipped", OrderDate =  DateTime.Parse("2025-09-20"), Amount = 122.68 },
                new OrdersTrackData { OrderID = "ORD1221", CustomerName = "Grace Lee", Product = "Laptop", Status = "Shipped", OrderDate =  DateTime.Parse("2025-09-27"), Amount = 670.46 },
                new OrdersTrackData { OrderID = "ORD1222", CustomerName = "David Brown", Product = "Tablet", Status = "Pending", OrderDate =  DateTime.Parse("2025-01-04"), Amount = 212.38 },
                new OrdersTrackData { OrderID = "ORD1223", CustomerName = "Frank Miller", Product = "Laptop", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-06-17"), Amount = 128.78 },
                new OrdersTrackData { OrderID = "ORD1224", CustomerName = "Olivia Purple", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-07-14"), Amount = 537.26 },
                new OrdersTrackData { OrderID = "ORD1225", CustomerName = "Ivy White", Product = "Shoe", Status = "Canceled", OrderDate =  DateTime.Parse("2025-02-06"), Amount = 403.10 },
                new OrdersTrackData { OrderID = "ORD1226", CustomerName = "Olivia Purple", Product = "Shirt", Status = "In Transit", OrderDate =  DateTime.Parse("2025-02-09"), Amount = 863.49 },
                new OrdersTrackData { OrderID = "ORD1227", CustomerName = "Kelly Gray", Product = "Tablet", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-05-29"), Amount = 124.02 },
                new OrdersTrackData { OrderID = "ORD1228", CustomerName = "Mia Blue", Product = "Watch", Status = "Delivered", OrderDate =  DateTime.Parse("2025-12-20"), Amount = 920.57 },
                new OrdersTrackData { OrderID = "ORD1229", CustomerName = "Olivia Purple", Product = "Bag", Status = "Shipped", OrderDate =  DateTime.Parse("2025-08-12"), Amount = 592.98 },
                new OrdersTrackData { OrderID = "ORD1230", CustomerName = "Henry Taylor", Product = "Tablet", Status = "In Transit", OrderDate =  DateTime.Parse("2025-06-23"), Amount = 229.36 },
                new OrdersTrackData { OrderID = "ORD1231", CustomerName = "Henry Taylor", Product = "Shoe", Status = "Pending", OrderDate =  DateTime.Parse("2025-09-29"), Amount = 514.85 },
                new OrdersTrackData { OrderID = "ORD1232", CustomerName = "Rose Pink", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-02-22"), Amount = 154.98 },
                new OrdersTrackData { OrderID = "ORD1233", CustomerName = "Alice Johnson", Product = "Book", Status = "Shipped", OrderDate =  DateTime.Parse("2025-12-02"), Amount = 84.60 },
                new OrdersTrackData { OrderID = "ORD1234", CustomerName = "Leo Red", Product = "Book", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-12-15"), Amount = 924.91 },
                new OrdersTrackData { OrderID = "ORD1235", CustomerName = "Mia Blue", Product = "Watch", Status = "Canceled", OrderDate =  DateTime.Parse("2025-02-04"), Amount = 474.23 },
                new OrdersTrackData { OrderID = "ORD1236", CustomerName = "John Doe", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-06-30"), Amount = 512.26 },
                new OrdersTrackData { OrderID = "ORD1237", CustomerName = "Leo Red", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-01-30"), Amount = 375.05 },
                new OrdersTrackData { OrderID = "ORD1238", CustomerName = "Henry Taylor", Product = "Bag", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-08-25"), Amount = 584.53 },
                new OrdersTrackData { OrderID = "ORD1239", CustomerName = "Leo Red", Product = "Book", Status = "Shipped", OrderDate =  DateTime.Parse("2025-06-14"), Amount = 608.96 },
                new OrdersTrackData { OrderID = "ORD1240", CustomerName = "Frank Miller", Product = "Shirt", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-02-22"), Amount = 812.86 },
                new OrdersTrackData { OrderID = "ORD1241", CustomerName = "Henry Taylor", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-01-21"), Amount = 255.27 },
                new OrdersTrackData { OrderID = "ORD1242", CustomerName = "Leo Red", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-07-06"), Amount = 379.12 },
                new OrdersTrackData { OrderID = "ORD1243", CustomerName = "Quinn Yellow", Product = "Tablet", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-12-14"), Amount = 601.91 },
                new OrdersTrackData { OrderID = "ORD1244", CustomerName = "Henry Taylor", Product = "Phone", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-13"), Amount = 681.60 },
                new OrdersTrackData { OrderID = "ORD1245", CustomerName = "John Doe", Product = "Book", Status = "Shipped", OrderDate =  DateTime.Parse("2025-06-20"), Amount = 90.69 },
                new OrdersTrackData { OrderID = "ORD1246", CustomerName = "Rose Pink", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-03-08"), Amount = 599.09 },
                new OrdersTrackData { OrderID = "ORD1247", CustomerName = "Bob Wilson", Product = "Shoe", Status = "In Transit", OrderDate =  DateTime.Parse("2025-11-26"), Amount = 793.75 },
                new OrdersTrackData { OrderID = "ORD1248", CustomerName = "Ivy White", Product = "Bag", Status = "In Transit", OrderDate =  DateTime.Parse("2025-09-18"), Amount = 368.21 },
                new OrdersTrackData { OrderID = "ORD1249", CustomerName = "Bob Wilson", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-06-24"), Amount = 948.19 },
                new OrdersTrackData { OrderID = "ORD1250", CustomerName = "Carol Davis", Product = "Headphone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-03-21"), Amount = 86.39 },
                new OrdersTrackData { OrderID = "ORD1251", CustomerName = "Ivy White", Product = "Shoe", Status = "Pending", OrderDate =  DateTime.Parse("2025-12-05"), Amount = 343.40 },
                new OrdersTrackData { OrderID = "ORD1252", CustomerName = "Noah Green", Product = "Tablet", Status = "Shipped", OrderDate =  DateTime.Parse("2025-03-25"), Amount = 189.04 },
                new OrdersTrackData { OrderID = "ORD1253", CustomerName = "Leo Red", Product = "Shirt", Status = "Canceled", OrderDate =  DateTime.Parse("2025-07-06"), Amount = 679.60 },
                new OrdersTrackData { OrderID = "ORD1254", CustomerName = "Leo Red", Product = "Book", Status = "In Transit", OrderDate =  DateTime.Parse("2025-08-18"), Amount = 241.66 },
                new OrdersTrackData { OrderID = "ORD1255", CustomerName = "Bob Wilson", Product = "Camera", Status = "Shipped", OrderDate =  DateTime.Parse("2025-07-08"), Amount = 681.52 },
                new OrdersTrackData { OrderID = "ORD1256", CustomerName = "Leo Red", Product = "Laptop", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-09-15"), Amount = 532.19 },
                new OrdersTrackData { OrderID = "ORD1257", CustomerName = "Carol Davis", Product = "Book", Status = "Shipped", OrderDate =  DateTime.Parse("2025-05-09"), Amount = 61.66 },
                new OrdersTrackData { OrderID = "ORD1258", CustomerName = "Rose Pink", Product = "Shoe", Status = "Pending", OrderDate =  DateTime.Parse("2025-12-31"), Amount = 847.43 },
                new OrdersTrackData { OrderID = "ORD1259", CustomerName = "Bob Wilson", Product = "Bag", Status = "Shipped", OrderDate =  DateTime.Parse("2025-05-20"), Amount = 454.83 },
                new OrdersTrackData { OrderID = "ORD1260", CustomerName = "Frank Miller", Product = "Tablet", Status = "Pending", OrderDate =  DateTime.Parse("2025-04-24"), Amount = 818.54 },
                new OrdersTrackData { OrderID = "ORD1261", CustomerName = "Eve Green", Product = "Tablet", Status = "Canceled", OrderDate =  DateTime.Parse("2025-07-22"), Amount = 506.99 },
                new OrdersTrackData { OrderID = "ORD1262", CustomerName = "Quinn Yellow", Product = "Bag", Status = "Pending", OrderDate =  DateTime.Parse("2025-04-25"), Amount = 37.91 },
                new OrdersTrackData { OrderID = "ORD1263", CustomerName = "Mia Blue", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-01-20"), Amount = 294.01 },
                new OrdersTrackData { OrderID = "ORD1264", CustomerName = "Frank Miller", Product = "Camera", Status = "In Transit", OrderDate =  DateTime.Parse("2025-11-12"), Amount = 15.20 },
                new OrdersTrackData { OrderID = "ORD1265", CustomerName = "Eve Green", Product = "Laptop", Status = "Delivered", OrderDate =  DateTime.Parse("2025-03-18"), Amount = 553.32 },
                new OrdersTrackData { OrderID = "ORD1266", CustomerName = "Olivia Purple", Product = "Bag", Status = "Shipped", OrderDate =  DateTime.Parse("2025-05-02"), Amount = 308.14 },
                new OrdersTrackData { OrderID = "ORD1267", CustomerName = "David Brown", Product = "Tablet", Status = "In Transit", OrderDate =  DateTime.Parse("2025-02-02"), Amount = 119.75 },
                new OrdersTrackData { OrderID = "ORD1268", CustomerName = "Noah Green", Product = "Shoe", Status = "Pending", OrderDate =  DateTime.Parse("2025-11-20"), Amount = 520.22 },
                new OrdersTrackData { OrderID = "ORD1269", CustomerName = "Frank Miller", Product = "Laptop", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-01-01"), Amount = 618.66 },
                new OrdersTrackData { OrderID = "ORD1270", CustomerName = "Kelly Gray", Product = "Tablet", Status = "Shipped", OrderDate =  DateTime.Parse("2025-12-07"), Amount = 671.53 },
                new OrdersTrackData { OrderID = "ORD1271", CustomerName = "Rose Pink", Product = "Bag", Status = "Pending", OrderDate =  DateTime.Parse("2025-07-19"), Amount = 874.60 },
                new OrdersTrackData { OrderID = "ORD1272", CustomerName = "Quinn Yellow", Product = "Phone", Status = "In Transit", OrderDate =  DateTime.Parse("2025-01-09"), Amount = 363.52 },
                new OrdersTrackData { OrderID = "ORD1273", CustomerName = "Rose Pink", Product = "Headphone", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-25"), Amount = 737.84 },
                new OrdersTrackData { OrderID = "ORD1274", CustomerName = "Frank Miller", Product = "Shirt", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-10-07"), Amount = 345.16 },
                new OrdersTrackData { OrderID = "ORD1275", CustomerName = "Leo Red", Product = "Camera", Status = "Shipped", OrderDate =  DateTime.Parse("2025-03-11"), Amount = 72.47 },
                new OrdersTrackData { OrderID = "ORD1276", CustomerName = "Jane Smith", Product = "Laptop", Status = "Shipped", OrderDate =  DateTime.Parse("2025-01-23"), Amount = 793.20 },
                new OrdersTrackData { OrderID = "ORD1277", CustomerName = "Mia Blue", Product = "Laptop", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-10-06"), Amount = 478.67 },
                new OrdersTrackData { OrderID = "ORD1278", CustomerName = "Carol Davis", Product = "Laptop", Status = "Shipped", OrderDate =  DateTime.Parse("2025-01-25"), Amount = 867.14 },
                new OrdersTrackData { OrderID = "ORD1279", CustomerName = "John Doe", Product = "Bag", Status = "Pending", OrderDate =  DateTime.Parse("2025-08-12"), Amount = 890.59 },
                new OrdersTrackData { OrderID = "ORD1280", CustomerName = "Quinn Yellow", Product = "Phone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-09-12"), Amount = 695.15 },
                new OrdersTrackData { OrderID = "ORD1281", CustomerName = "Ivy White", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-08-06"), Amount = 88.14 },
                new OrdersTrackData { OrderID = "ORD1282", CustomerName = "Jack Black", Product = "Laptop", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-02-22"), Amount = 89.27 },
                new OrdersTrackData { OrderID = "ORD1283", CustomerName = "Bob Wilson", Product = "Camera", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-03-27"), Amount = 692.87 },
                new OrdersTrackData { OrderID = "ORD1284", CustomerName = "Leo Red", Product = "Shirt", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-11-11"), Amount = 998.17 },
                new OrdersTrackData { OrderID = "ORD1285", CustomerName = "Jane Smith", Product = "Bag", Status = "Pending", OrderDate =  DateTime.Parse("2025-07-06"), Amount = 517.96 },
                new OrdersTrackData { OrderID = "ORD1286", CustomerName = "Eve Green", Product = "Watch", Status = "In Transit", OrderDate =  DateTime.Parse("2025-01-18"), Amount = 134.97 },
                new OrdersTrackData { OrderID = "ORD1287", CustomerName = "Rose Pink", Product = "Phone", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-10-18"), Amount = 42.06 },
                new OrdersTrackData { OrderID = "ORD1288", CustomerName = "Leo Red", Product = "Phone", Status = "Pending", OrderDate =  DateTime.Parse("2025-08-16"), Amount = 765.45 },
                new OrdersTrackData { OrderID = "ORD1289", CustomerName = "Ivy White", Product = "Phone", Status = "In Transit", OrderDate =  DateTime.Parse("2025-06-10"), Amount = 653.07 },
                new OrdersTrackData { OrderID = "ORD1290", CustomerName = "Grace Lee", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-09-13"), Amount = 522.57 },
                new OrdersTrackData { OrderID = "ORD1291", CustomerName = "John Doe", Product = "Laptop", Status = "Shipped", OrderDate =  DateTime.Parse("2025-04-20"), Amount = 996.40 },
                new OrdersTrackData { OrderID = "ORD1292", CustomerName = "Paul Orange", Product = "Headphone", Status = "Pending", OrderDate =  DateTime.Parse("2025-03-11"), Amount = 854.30 },
                new OrdersTrackData { OrderID = "ORD1293", CustomerName = "Alice Johnson", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-12-16"), Amount = 967.89 },
                new OrdersTrackData { OrderID = "ORD1294", CustomerName = "Rose Pink", Product = "Bag", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-06-03"), Amount = 852.85 },
                new OrdersTrackData { OrderID = "ORD1295", CustomerName = "Rose Pink", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-03-04"), Amount = 985.28 },
                new OrdersTrackData { OrderID = "ORD1296", CustomerName = "David Brown", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-07-04"), Amount = 558.48 },
                new OrdersTrackData { OrderID = "ORD1297", CustomerName = "Leo Red", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-11-10"), Amount = 885.40 },
                new OrdersTrackData { OrderID = "ORD1298", CustomerName = "Bob Wilson", Product = "Tablet", Status = "Shipped", OrderDate =  DateTime.Parse("2025-09-27"), Amount = 416.69 },
                new OrdersTrackData { OrderID = "ORD1299", CustomerName = "Kelly Gray", Product = "Bag", Status = "Shipped", OrderDate =  DateTime.Parse("2025-06-12"), Amount = 645.92 },
                new OrdersTrackData { OrderID = "ORD1300", CustomerName = "Leo Red", Product = "Shoe", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-03-07"), Amount = 879.18 },
                new OrdersTrackData { OrderID = "ORD1301", CustomerName = "Frank Miller", Product = "Tablet", Status = "Pending", OrderDate =  DateTime.Parse("2025-03-05"), Amount = 522.92 },
                new OrdersTrackData { OrderID = "ORD1302", CustomerName = "Alice Johnson", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-12-30"), Amount = 233.22 },
                new OrdersTrackData { OrderID = "ORD1303", CustomerName = "Bob Wilson", Product = "Bag", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-04-11"), Amount = 638.71 },
                new OrdersTrackData { OrderID = "ORD1304", CustomerName = "Frank Miller", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-09-15"), Amount = 644.58 },
                new OrdersTrackData { OrderID = "ORD1305", CustomerName = "Alice Johnson", Product = "Book", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-10-16"), Amount = 50.78 },
                new OrdersTrackData { OrderID = "ORD1306", CustomerName = "Henry Taylor", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-11-30"), Amount = 218.70 },
                new OrdersTrackData { OrderID = "ORD1307", CustomerName = "Noah Green", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-11-18"), Amount = 550.12 },
                new OrdersTrackData { OrderID = "ORD1308", CustomerName = "Paul Orange", Product = "Headphone", Status = "In Transit", OrderDate =  DateTime.Parse("2025-06-02"), Amount = 459.01 },
                new OrdersTrackData { OrderID = "ORD1309", CustomerName = "Alice Johnson", Product = "Camera", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-09-05"), Amount = 469.80 },
                new OrdersTrackData { OrderID = "ORD1310", CustomerName = "Noah Green", Product = "Watch", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-06-13"), Amount = 736.86 },
                new OrdersTrackData { OrderID = "ORD1311", CustomerName = "Quinn Yellow", Product = "Watch", Status = "In Transit", OrderDate =  DateTime.Parse("2025-09-21"), Amount = 566.03 },
                new OrdersTrackData { OrderID = "ORD1312", CustomerName = "David Brown", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-05-17"), Amount = 455.10 },
                new OrdersTrackData { OrderID = "ORD1313", CustomerName = "Grace Lee", Product = "Shirt", Status = "In Transit", OrderDate =  DateTime.Parse("2025-07-16"), Amount = 865.52 },
                new OrdersTrackData { OrderID = "ORD1314", CustomerName = "David Brown", Product = "Watch", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-23"), Amount = 723.92 },
                new OrdersTrackData { OrderID = "ORD1315", CustomerName = "Alice Johnson", Product = "Camera", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-09-13"), Amount = 880.28 },
                new OrdersTrackData { OrderID = "ORD1316", CustomerName = "Eve Green", Product = "Bag", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-09-16"), Amount = 462.66 },
                new OrdersTrackData { OrderID = "ORD1317", CustomerName = "Carol Davis", Product = "Book", Status = "Canceled", OrderDate =  DateTime.Parse("2025-01-25"), Amount = 60.04 },
                new OrdersTrackData { OrderID = "ORD1318", CustomerName = "Noah Green", Product = "Camera", Status = "In Transit", OrderDate =  DateTime.Parse("2025-10-02"), Amount = 18.10 },
                new OrdersTrackData { OrderID = "ORD1319", CustomerName = "Olivia Purple", Product = "Watch", Status = "Canceled", OrderDate =  DateTime.Parse("2025-07-07"), Amount = 766.22 },
                new OrdersTrackData { OrderID = "ORD1320", CustomerName = "Jane Smith", Product = "Tablet", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-19"), Amount = 566.20 },
                new OrdersTrackData { OrderID = "ORD1321", CustomerName = "Jack Black", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-07-17"), Amount = 509.21 },
                new OrdersTrackData { OrderID = "ORD1322", CustomerName = "Noah Green", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-03-07"), Amount = 975.33 },
                new OrdersTrackData { OrderID = "ORD1323", CustomerName = "Rose Pink", Product = "Phone", Status = "Delivered", OrderDate =  DateTime.Parse("2025-03-15"), Amount = 207.07 },
                new OrdersTrackData { OrderID = "ORD1324", CustomerName = "Quinn Yellow", Product = "Shoe", Status = "Pending", OrderDate =  DateTime.Parse("2025-01-24"), Amount = 48.52 },
                new OrdersTrackData { OrderID = "ORD1325", CustomerName = "Paul Orange", Product = "Shoe", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-03-18"), Amount = 610.20 },
                new OrdersTrackData { OrderID = "ORD1326", CustomerName = "Frank Miller", Product = "Phone", Status = "Canceled", OrderDate =  DateTime.Parse("2025-03-25"), Amount = 399.03 },
                new OrdersTrackData { OrderID = "ORD1327", CustomerName = "Kelly Gray", Product = "Phone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-12-29"), Amount = 567.30 },
                new OrdersTrackData { OrderID = "ORD1328", CustomerName = "Eve Green", Product = "Phone", Status = "In Transit", OrderDate =  DateTime.Parse("2025-12-11"), Amount = 118.51 },
                new OrdersTrackData { OrderID = "ORD1329", CustomerName = "Kelly Gray", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-11-02"), Amount = 479.84 },
                new OrdersTrackData { OrderID = "ORD1330", CustomerName = "Jane Smith", Product = "Book", Status = "In Transit", OrderDate =  DateTime.Parse("2025-03-29"), Amount = 528.99 },
                new OrdersTrackData { OrderID = "ORD1331", CustomerName = "Frank Miller", Product = "Headphone", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-21"), Amount = 948.72 },
                new OrdersTrackData { OrderID = "ORD1332", CustomerName = "Carol Davis", Product = "Shirt", Status = "In Transit", OrderDate =  DateTime.Parse("2025-06-10"), Amount = 424.59 },
                new OrdersTrackData { OrderID = "ORD1333", CustomerName = "Carol Davis", Product = "Tablet", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-02-01"), Amount = 708.72 },
                new OrdersTrackData { OrderID = "ORD1334", CustomerName = "Carol Davis", Product = "Shoe", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-12-06"), Amount = 483.59 },
                new OrdersTrackData { OrderID = "ORD1335", CustomerName = "Mia Blue", Product = "Watch", Status = "In Transit", OrderDate =  DateTime.Parse("2025-09-30"), Amount = 348.90 },
                new OrdersTrackData { OrderID = "ORD1336", CustomerName = "John Doe", Product = "Book", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-04-09"), Amount = 957.76 },
                new OrdersTrackData { OrderID = "ORD1337", CustomerName = "Jack Black", Product = "Laptop", Status = "Shipped", OrderDate =  DateTime.Parse("2025-06-02"), Amount = 773.46 },
                new OrdersTrackData { OrderID = "ORD1338", CustomerName = "Paul Orange", Product = "Phone", Status = "Pending", OrderDate =  DateTime.Parse("2025-06-28"), Amount = 564.88 },
                new OrdersTrackData { OrderID = "ORD1339", CustomerName = "Bob Wilson", Product = "Bag", Status = "Canceled", OrderDate =  DateTime.Parse("2025-07-22"), Amount = 820.19 },
                new OrdersTrackData { OrderID = "ORD1340", CustomerName = "Bob Wilson", Product = "Shirt", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-02-10"), Amount = 352.90 },
                new OrdersTrackData { OrderID = "ORD1341", CustomerName = "John Doe", Product = "Camera", Status = "Shipped", OrderDate =  DateTime.Parse("2025-04-14"), Amount = 829.67 },
                new OrdersTrackData { OrderID = "ORD1342", CustomerName = "Jack Black", Product = "Laptop", Status = "Shipped", OrderDate =  DateTime.Parse("2025-02-25"), Amount = 619.52 },
                new OrdersTrackData { OrderID = "ORD1343", CustomerName = "David Brown", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-11-23"), Amount = 240.51 },
                new OrdersTrackData { OrderID = "ORD1344", CustomerName = "Olivia Purple", Product = "Phone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-02-21"), Amount = 684.38 },
                new OrdersTrackData { OrderID = "ORD1345", CustomerName = "Eve Green", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-07-28"), Amount = 656.36 },
                new OrdersTrackData { OrderID = "ORD1346", CustomerName = "Paul Orange", Product = "Headphone", Status = "In Transit", OrderDate =  DateTime.Parse("2025-06-14"), Amount = 292.56 },
                new OrdersTrackData { OrderID = "ORD1347", CustomerName = "Henry Taylor", Product = "Book", Status = "Shipped", OrderDate =  DateTime.Parse("2025-10-01"), Amount = 741.30 },
                new OrdersTrackData { OrderID = "ORD1348", CustomerName = "Alice Johnson", Product = "Tablet", Status = "Shipped", OrderDate =  DateTime.Parse("2025-01-19"), Amount = 997.20 },
                new OrdersTrackData { OrderID = "ORD1349", CustomerName = "Paul Orange", Product = "Watch", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-01-20"), Amount = 19.17 },
                new OrdersTrackData { OrderID = "ORD1350", CustomerName = "Mia Blue", Product = "Laptop", Status = "Shipped", OrderDate =  DateTime.Parse("2025-11-25"), Amount = 547.87 },
                new OrdersTrackData { OrderID = "ORD1351", CustomerName = "Frank Miller", Product = "Shoe", Status = "Canceled", OrderDate =  DateTime.Parse("2025-05-20"), Amount = 200.88 },
                new OrdersTrackData { OrderID = "ORD1352", CustomerName = "Mia Blue", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-11-28"), Amount = 264.69 },
                new OrdersTrackData { OrderID = "ORD1353", CustomerName = "Eve Green", Product = "Phone", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-10-18"), Amount = 677.66 },
                new OrdersTrackData { OrderID = "ORD1354", CustomerName = "Alice Johnson", Product = "Book", Status = "In Transit", OrderDate =  DateTime.Parse("2025-08-07"), Amount = 520.13 },
                new OrdersTrackData { OrderID = "ORD1355", CustomerName = "Quinn Yellow", Product = "Bag", Status = "Shipped", OrderDate =  DateTime.Parse("2025-03-13"), Amount = 482.68 },
                new OrdersTrackData { OrderID = "ORD1356", CustomerName = "Eve Green", Product = "Laptop", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-05-01"), Amount = 452.27 },
                new OrdersTrackData { OrderID = "ORD1357", CustomerName = "Mia Blue", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-05-14"), Amount = 657.15 },
                new OrdersTrackData { OrderID = "ORD1358", CustomerName = "Jane Smith", Product = "Bag", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-06-07"), Amount = 168.12 },
                new OrdersTrackData { OrderID = "ORD1359", CustomerName = "Bob Wilson", Product = "Bag", Status = "Delivered", OrderDate =  DateTime.Parse("2025-07-08"), Amount = 618.48 },
                new OrdersTrackData { OrderID = "ORD1360", CustomerName = "Frank Miller", Product = "Camera", Status = "Shipped", OrderDate =  DateTime.Parse("2025-08-21"), Amount = 750.26 },
                new OrdersTrackData { OrderID = "ORD1361", CustomerName = "Olivia Purple", Product = "Shoe", Status = "In Transit", OrderDate =  DateTime.Parse("2025-10-03"), Amount = 803.98 },
                new OrdersTrackData { OrderID = "ORD1362", CustomerName = "David Brown", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-09-27"), Amount = 452.28 },
                new OrdersTrackData { OrderID = "ORD1363", CustomerName = "Henry Taylor", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-02-01"), Amount = 830.49 },
                new OrdersTrackData { OrderID = "ORD1364", CustomerName = "Carol Davis", Product = "Book", Status = "Shipped", OrderDate =  DateTime.Parse("2025-03-26"), Amount = 334.84 },
                new OrdersTrackData { OrderID = "ORD1365", CustomerName = "Leo Red", Product = "Bag", Status = "Shipped", OrderDate =  DateTime.Parse("2025-10-26"), Amount = 493.94 },
                new OrdersTrackData { OrderID = "ORD1366", CustomerName = "Leo Red", Product = "Shirt", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-03-09"), Amount = 518.12 },
                new OrdersTrackData { OrderID = "ORD1367", CustomerName = "Kelly Gray", Product = "Shirt", Status = "Pending", OrderDate =  DateTime.Parse("2025-12-11"), Amount = 808.85 },
                new OrdersTrackData { OrderID = "ORD1368", CustomerName = "Quinn Yellow", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-04-22"), Amount = 582.53 },
                new OrdersTrackData { OrderID = "ORD1369", CustomerName = "Olivia Purple", Product = "Phone", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-05"), Amount = 994.18 },
                new OrdersTrackData { OrderID = "ORD1370", CustomerName = "Paul Orange", Product = "Shirt", Status = "Pending", OrderDate =  DateTime.Parse("2025-07-29"), Amount = 188.18 },
                new OrdersTrackData { OrderID = "ORD1371", CustomerName = "Olivia Purple", Product = "Phone", Status = "In Transit", OrderDate =  DateTime.Parse("2025-08-18"), Amount = 870.92 },
                new OrdersTrackData { OrderID = "ORD1372", CustomerName = "Quinn Yellow", Product = "Bag", Status = "Shipped", OrderDate =  DateTime.Parse("2025-12-01"), Amount = 861.68 },
                new OrdersTrackData { OrderID = "ORD1373", CustomerName = "Alice Johnson", Product = "Shoe", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-09-28"), Amount = 136.07 },
                new OrdersTrackData { OrderID = "ORD1374", CustomerName = "Eve Green", Product = "Shirt", Status = "Canceled", OrderDate =  DateTime.Parse("2025-08-26"), Amount = 676.76 },
                new OrdersTrackData { OrderID = "ORD1375", CustomerName = "Olivia Purple", Product = "Shoe", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-04-28"), Amount = 255.04 },
                new OrdersTrackData { OrderID = "ORD1376", CustomerName = "Frank Miller", Product = "Laptop", Status = "Shipped", OrderDate =  DateTime.Parse("2025-02-27"), Amount = 41.90 },
                new OrdersTrackData { OrderID = "ORD1377", CustomerName = "Noah Green", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-04-16"), Amount = 76.62 },
                new OrdersTrackData { OrderID = "ORD1378", CustomerName = "Leo Red", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-05-06"), Amount = 743.14 },
                new OrdersTrackData { OrderID = "ORD1379", CustomerName = "Leo Red", Product = "Headphone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-01-29"), Amount = 148.73 },
                new OrdersTrackData { OrderID = "ORD1380", CustomerName = "David Brown", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-23"), Amount = 601.94 },
                new OrdersTrackData { OrderID = "ORD1381", CustomerName = "David Brown", Product = "Laptop", Status = "Shipped", OrderDate =  DateTime.Parse("2025-12-05"), Amount = 526.04 },
                new OrdersTrackData { OrderID = "ORD1382", CustomerName = "Bob Wilson", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-13"), Amount = 949.04 },
                new OrdersTrackData { OrderID = "ORD1383", CustomerName = "Olivia Purple", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-01-25"), Amount = 972.57 },
                new OrdersTrackData { OrderID = "ORD1384", CustomerName = "Ivy White", Product = "Phone", Status = "Pending", OrderDate =  DateTime.Parse("2025-07-29"), Amount = 157.73 },
                new OrdersTrackData { OrderID = "ORD1385", CustomerName = "Alice Johnson", Product = "Shoe", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-05-04"), Amount = 850.85 },
                new OrdersTrackData { OrderID = "ORD1386", CustomerName = "Frank Miller", Product = "Camera", Status = "Delivered", OrderDate =  DateTime.Parse("2025-10-15"), Amount = 418.55 },
                new OrdersTrackData { OrderID = "ORD1387", CustomerName = "Jack Black", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-07-18"), Amount = 250.43 },
                new OrdersTrackData { OrderID = "ORD1388", CustomerName = "Mia Blue", Product = "Bag", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-07-09"), Amount = 101.54 },
                new OrdersTrackData { OrderID = "ORD1389", CustomerName = "Jane Smith", Product = "Laptop", Status = "Shipped", OrderDate =  DateTime.Parse("2025-12-11"), Amount = 608.92 },
                new OrdersTrackData { OrderID = "ORD1390", CustomerName = "Henry Taylor", Product = "Headphone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-09-03"), Amount = 216.80 },
                new OrdersTrackData { OrderID = "ORD1391", CustomerName = "Bob Wilson", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-04-08"), Amount = 962.46 },
                new OrdersTrackData { OrderID = "ORD1392", CustomerName = "Paul Orange", Product = "Headphone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-07-23"), Amount = 915.98 },
                new OrdersTrackData { OrderID = "ORD1393", CustomerName = "Bob Wilson", Product = "Tablet", Status = "In Transit", OrderDate =  DateTime.Parse("2025-10-01"), Amount = 652.23 },
                new OrdersTrackData { OrderID = "ORD1394", CustomerName = "John Doe", Product = "Phone", Status = "Delivered", OrderDate =  DateTime.Parse("2025-08-27"), Amount = 107.62 },
                new OrdersTrackData { OrderID = "ORD1395", CustomerName = "Mia Blue", Product = "Headphone", Status = "Pending", OrderDate =  DateTime.Parse("2025-06-10"), Amount = 419.79 },
                new OrdersTrackData { OrderID = "ORD1396", CustomerName = "Frank Miller", Product = "Shirt", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-10-11"), Amount = 935.41 },
                new OrdersTrackData { OrderID = "ORD1397", CustomerName = "Bob Wilson", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-06-18"), Amount = 237.72 },
                new OrdersTrackData { OrderID = "ORD1398", CustomerName = "Paul Orange", Product = "Shoe", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-05-12"), Amount = 765.73 },
                new OrdersTrackData { OrderID = "ORD1399", CustomerName = "Paul Orange", Product = "Camera", Status = "Delivered", OrderDate =  DateTime.Parse("2025-06-30"), Amount = 177.57 },
                new OrdersTrackData { OrderID = "ORD1400", CustomerName = "Paul Orange", Product = "Watch", Status = "Pending", OrderDate =  DateTime.Parse("2025-09-26"), Amount = 43.49 },
                new OrdersTrackData { OrderID = "ORD1401", CustomerName = "Jane Smith", Product = "Shirt", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-03-12"), Amount = 844.12 },
                new OrdersTrackData { OrderID = "ORD1402", CustomerName = "Henry Taylor", Product = "Watch", Status = "Pending", OrderDate =  DateTime.Parse("2025-04-22"), Amount = 510.68 },
                new OrdersTrackData { OrderID = "ORD1403", CustomerName = "Jane Smith", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-12-04"), Amount = 492.98 },
                new OrdersTrackData { OrderID = "ORD1404", CustomerName = "Jack Black", Product = "Shoe", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-01-07"), Amount = 26.56 },
                new OrdersTrackData { OrderID = "ORD1405", CustomerName = "Jack Black", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-09-15"), Amount = 815.03 },
                new OrdersTrackData { OrderID = "ORD1406", CustomerName = "Alice Johnson", Product = "Bag", Status = "Pending", OrderDate =  DateTime.Parse("2025-09-26"), Amount = 157.41 },
                new OrdersTrackData { OrderID = "ORD1407", CustomerName = "Noah Green", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-07-01"), Amount = 274.65 },
                new OrdersTrackData { OrderID = "ORD1408", CustomerName = "Henry Taylor", Product = "Phone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-08-24"), Amount = 569.35 },
                new OrdersTrackData { OrderID = "ORD1409", CustomerName = "Bob Wilson", Product = "Bag", Status = "Pending", OrderDate =  DateTime.Parse("2025-02-17"), Amount = 411.23 },
                new OrdersTrackData { OrderID = "ORD1410", CustomerName = "Jack Black", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-11-23"), Amount = 19.36 },
                new OrdersTrackData { OrderID = "ORD1411", CustomerName = "Henry Taylor", Product = "Camera", Status = "Canceled", OrderDate =  DateTime.Parse("2025-11-27"), Amount = 786.53 },
                new OrdersTrackData { OrderID = "ORD1412", CustomerName = "Ivy White", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-04-19"), Amount = 902.26 },
                new OrdersTrackData { OrderID = "ORD1413", CustomerName = "John Doe", Product = "Shirt", Status = "Pending", OrderDate =  DateTime.Parse("2025-12-17"), Amount = 926.33 },
                new OrdersTrackData { OrderID = "ORD1414", CustomerName = "Kelly Gray", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-06-11"), Amount = 25.50 },
                new OrdersTrackData { OrderID = "ORD1415", CustomerName = "Kelly Gray", Product = "Watch", Status = "Pending", OrderDate =  DateTime.Parse("2025-02-09"), Amount = 306.28 },
                new OrdersTrackData { OrderID = "ORD1416", CustomerName = "Kelly Gray", Product = "Tablet", Status = "Canceled", OrderDate =  DateTime.Parse("2025-07-16"), Amount = 758.05 },
                new OrdersTrackData { OrderID = "ORD1417", CustomerName = "Henry Taylor", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-01-28"), Amount = 106.71 },
                new OrdersTrackData { OrderID = "ORD1418", CustomerName = "Henry Taylor", Product = "Phone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-06-17"), Amount = 39.33 },
                new OrdersTrackData { OrderID = "ORD1419", CustomerName = "Leo Red", Product = "Camera", Status = "Shipped", OrderDate =  DateTime.Parse("2025-07-02"), Amount = 557.51 },
                new OrdersTrackData { OrderID = "ORD1420", CustomerName = "Olivia Purple", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-02-13"), Amount = 774.45 },
                new OrdersTrackData { OrderID = "ORD1421", CustomerName = "David Brown", Product = "Bag", Status = "Pending", OrderDate =  DateTime.Parse("2025-05-18"), Amount = 162.68 },
                new OrdersTrackData { OrderID = "ORD1422", CustomerName = "Quinn Yellow", Product = "Phone", Status = "Delivered", OrderDate =  DateTime.Parse("2025-02-24"), Amount = 100.61 },
                new OrdersTrackData { OrderID = "ORD1423", CustomerName = "Leo Red", Product = "Phone", Status = "Canceled", OrderDate =  DateTime.Parse("2025-02-22"), Amount = 141.18 },
                new OrdersTrackData { OrderID = "ORD1424", CustomerName = "Olivia Purple", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-02-22"), Amount = 36.00 },
                new OrdersTrackData { OrderID = "ORD1425", CustomerName = "Jack Black", Product = "Bag", Status = "Out For Delivery", OrderDate =  DateTime.Parse("2025-07-17"), Amount = 22.22 },
                new OrdersTrackData { OrderID = "ORD1426", CustomerName = "Quinn Yellow", Product = "Bag", Status = "Shipped", OrderDate =  DateTime.Parse("2025-10-20"), Amount = 525.89 },
                new OrdersTrackData { OrderID = "ORD1427", CustomerName = "Alice Johnson", Product = "Watch", Status = "Delivered", OrderDate =  DateTime.Parse("2025-06-04"), Amount = 275.72 },
                new OrdersTrackData { OrderID = "ORD1428", CustomerName = "Henry Taylor", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-05-22"), Amount = 426.89 },
                new OrdersTrackData { OrderID = "ORD1429", CustomerName = "Henry Taylor", Product = "Phone", Status = "In Transit", OrderDate =  DateTime.Parse("2025-05-07"), Amount = 723.69 },
                new OrdersTrackData { OrderID = "ORD1430", CustomerName = "Noah Green", Product = "Book", Status = "Shipped", OrderDate =  DateTime.Parse("2025-08-23"), Amount = 115.90 },
                new OrdersTrackData { OrderID = "ORD1431", CustomerName = "Eve Green", Product = "Tablet", Status = "Pending", OrderDate =  DateTime.Parse("2025-11-14"), Amount = 386.09 },
                new OrdersTrackData { OrderID = "ORD1432", CustomerName = "Leo Red", Product = "Phone", Status = "Pending", OrderDate =  DateTime.Parse("2025-11-30"), Amount = 974.48 },
                new OrdersTrackData { OrderID = "ORD1433", CustomerName = "Bob Wilson", Product = "Phone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-09-03"), Amount = 321.04 },
                new OrdersTrackData { OrderID = "ORD1434", CustomerName = "Mia Blue", Product = "Laptop", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-10-22"), Amount = 784.15 },
                new OrdersTrackData { OrderID = "ORD1435", CustomerName = "Quinn Yellow", Product = "Laptop", Status = "Delivered", OrderDate =  DateTime.Parse("2025-07-06"), Amount = 122.75 },
                new OrdersTrackData { OrderID = "ORD1436", CustomerName = "Kelly Gray", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-12-16"), Amount = 769.94 },
                new OrdersTrackData { OrderID = "ORD1437", CustomerName = "Leo Red", Product = "Headphone", Status = "Canceled", OrderDate =  DateTime.Parse("2025-05-30"), Amount = 832.97 },
                new OrdersTrackData { OrderID = "ORD1438", CustomerName = "Olivia Purple", Product = "Camera", Status = "Shipped", OrderDate =  DateTime.Parse("2025-11-21"), Amount = 309.80 },
                new OrdersTrackData { OrderID = "ORD1439", CustomerName = "Frank Miller", Product = "Tablet", Status = "Pending", OrderDate =  DateTime.Parse("2025-02-07"), Amount = 454.58 },
                new OrdersTrackData { OrderID = "ORD1440", CustomerName = "Kelly Gray", Product = "Tablet", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-06"), Amount = 46.40 },
                new OrdersTrackData { OrderID = "ORD1441", CustomerName = "Jack Black", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-02-25"), Amount = 771.26 },
                new OrdersTrackData { OrderID = "ORD1442", CustomerName = "Alice Johnson", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-16"), Amount = 983.77 },
                new OrdersTrackData { OrderID = "ORD1443", CustomerName = "Mia Blue", Product = "Tablet", Status = "Delivered", OrderDate =  DateTime.Parse("2025-01-06"), Amount = 107.62 },
                new OrdersTrackData { OrderID = "ORD1444", CustomerName = "Ivy White", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-08-17"), Amount = 380.38 },
                new OrdersTrackData { OrderID = "ORD1445", CustomerName = "Kelly Gray", Product = "Shoe", Status = "Shipped", OrderDate =  DateTime.Parse("2025-06-26"), Amount = 997.73 },
                new OrdersTrackData { OrderID = "ORD1446", CustomerName = "Grace Lee", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-02-13"), Amount = 124.91 },
                new OrdersTrackData { OrderID = "ORD1447", CustomerName = "Rose Pink", Product = "Laptop", Status = "Delivered", OrderDate =  DateTime.Parse("2025-08-22"), Amount = 786.43 },
                new OrdersTrackData { OrderID = "ORD1448", CustomerName = "Paul Orange", Product = "Phone", Status = "In Transit", OrderDate =  DateTime.Parse("2025-02-19"), Amount = 443.78 },
                new OrdersTrackData { OrderID = "ORD1449", CustomerName = "Mia Blue", Product = "Bag", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-01-23"), Amount = 812.08 },
                new OrdersTrackData { OrderID = "ORD1450", CustomerName = "Eve Green", Product = "Phone", Status = "Pending", OrderDate =  DateTime.Parse("2025-12-13"), Amount = 802.05 },
                new OrdersTrackData { OrderID = "ORD1451", CustomerName = "Ivy White", Product = "Watch", Status = "Shipped", OrderDate =  DateTime.Parse("2025-06-19"), Amount = 564.25 },
                new OrdersTrackData { OrderID = "ORD1452", CustomerName = "David Brown", Product = "Tablet", Status = "Shipped", OrderDate =  DateTime.Parse("2025-04-06"), Amount = 644.07 },
                new OrdersTrackData { OrderID = "ORD1453", CustomerName = "Quinn Yellow", Product = "Shirt", Status = "Shipped", OrderDate =  DateTime.Parse("2025-08-19"), Amount = 596.28 },
                new OrdersTrackData { OrderID = "ORD1454", CustomerName = "Eve Green", Product = "Headphone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-05-23"), Amount = 754.80 },
                new OrdersTrackData { OrderID = "ORD1455", CustomerName = "Kelly Gray", Product = "Bag", Status = "Delivered", OrderDate =  DateTime.Parse("2025-07-07"), Amount = 332.73 },
                new OrdersTrackData { OrderID = "ORD1456", CustomerName = "Grace Lee", Product = "Laptop", Status = "Shipped", OrderDate =  DateTime.Parse("2025-09-28"), Amount = 966.26 },
                new OrdersTrackData { OrderID = "ORD1457", CustomerName = "Noah Green", Product = "Tablet", Status = "Canceled", OrderDate =  DateTime.Parse("2025-10-28"), Amount = 123.09 },
                new OrdersTrackData { OrderID = "ORD1458", CustomerName = "Leo Red", Product = "Book", Status = "Shipped", OrderDate =  DateTime.Parse("2025-12-11"), Amount = 708.93 },
                new OrdersTrackData { OrderID = "ORD1459", CustomerName = "Noah Green", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-12-11"), Amount = 142.61 },
                new OrdersTrackData { OrderID = "ORD1460", CustomerName = "David Brown", Product = "Laptop", Status = "Pending", OrderDate =  DateTime.Parse("2025-04-04"), Amount = 379.57 },
                new OrdersTrackData { OrderID = "ORD1461", CustomerName = "Ivy White", Product = "Tablet", Status = "In Transit", OrderDate =  DateTime.Parse("2025-11-02"), Amount = 146.49 },
                new OrdersTrackData { OrderID = "ORD1462", CustomerName = "Olivia Purple", Product = "Watch", Status = "In Transit", OrderDate =  DateTime.Parse("2025-11-22"), Amount = 542.01 },
                new OrdersTrackData { OrderID = "ORD1463", CustomerName = "Jack Black", Product = "Watch", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-05-28"), Amount = 148.89 },
                new OrdersTrackData { OrderID = "ORD1464", CustomerName = "Leo Red", Product = "Book", Status = "Pending", OrderDate =  DateTime.Parse("2025-07-03"), Amount = 952.32 },
                new OrdersTrackData { OrderID = "ORD1465", CustomerName = "Frank Miller", Product = "Headphone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-10-15"), Amount = 510.38 },
                new OrdersTrackData { OrderID = "ORD1466", CustomerName = "Olivia Purple", Product = "Camera", Status = "Canceled", OrderDate =  DateTime.Parse("2025-12-30"), Amount = 841.49 },
                new OrdersTrackData { OrderID = "ORD1467", CustomerName = "Alice Johnson", Product = "Bag", Status = "Pending", OrderDate =  DateTime.Parse("2025-04-23"), Amount = 299.17 },
                new OrdersTrackData { OrderID = "ORD1468", CustomerName = "David Brown", Product = "Shoe", Status = "Pending", OrderDate =  DateTime.Parse("2025-03-28"), Amount = 782.93 },
                new OrdersTrackData { OrderID = "ORD1469", CustomerName = "Jack Black", Product = "Shoe", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-21"), Amount = 123.06 },
                new OrdersTrackData { OrderID = "ORD1470", CustomerName = "Rose Pink", Product = "Shoe", Status = "Pending", OrderDate =  DateTime.Parse("2025-08-14"), Amount = 550.89 },
                new OrdersTrackData { OrderID = "ORD1471", CustomerName = "Grace Lee", Product = "Headphone", Status = "Delivered", OrderDate =  DateTime.Parse("2025-01-17"), Amount = 455.24 },
                new OrdersTrackData { OrderID = "ORD1472", CustomerName = "Henry Taylor", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-05-02"), Amount = 217.78 },
                new OrdersTrackData { OrderID = "ORD1473", CustomerName = "Noah Green", Product = "Tablet", Status = "Shipped", OrderDate =  DateTime.Parse("2025-11-12"), Amount = 147.84 },
                new OrdersTrackData { OrderID = "ORD1474", CustomerName = "Carol Davis", Product = "Shirt", Status = "In Transit", OrderDate =  DateTime.Parse("2025-09-30"), Amount = 288.27 },
                new OrdersTrackData { OrderID = "ORD1475", CustomerName = "Alice Johnson", Product = "Phone", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-05-29"), Amount = 577.01 },
                new OrdersTrackData { OrderID = "ORD1476", CustomerName = "Grace Lee", Product = "Watch", Status = "Canceled", OrderDate =  DateTime.Parse("2025-01-31"), Amount = 992.56 },
                new OrdersTrackData { OrderID = "ORD1477", CustomerName = "Frank Miller", Product = "Headphone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-12-31"), Amount = 328.88 },
                new OrdersTrackData { OrderID = "ORD1478", CustomerName = "Quinn Yellow", Product = "Camera", Status = "Shipped", OrderDate =  DateTime.Parse("2025-10-23"), Amount = 636.08 },
                new OrdersTrackData { OrderID = "ORD1479", CustomerName = "Quinn Yellow", Product = "Camera", Status = "Pending", OrderDate =  DateTime.Parse("2025-11-21"), Amount = 796.65 },
                new OrdersTrackData { OrderID = "ORD1480", CustomerName = "Quinn Yellow", Product = "Shoe", Status = "In Transit", OrderDate =  DateTime.Parse("2025-12-22"), Amount = 936.97 },
                new OrdersTrackData { OrderID = "ORD1481", CustomerName = "Leo Red", Product = "Camera", Status = "Shipped", OrderDate =  DateTime.Parse("2025-10-25"), Amount = 12.45 },
                new OrdersTrackData { OrderID = "ORD1482", CustomerName = "Leo Red", Product = "Phone", Status = "Pending", OrderDate =  DateTime.Parse("2025-10-01"), Amount = 403.74 },
                new OrdersTrackData { OrderID = "ORD1483", CustomerName = "Carol Davis", Product = "Camera", Status = "Canceled", OrderDate =  DateTime.Parse("2025-06-15"), Amount = 830.06 },
                new OrdersTrackData { OrderID = "ORD1484", CustomerName = "Jack Black", Product = "Book", Status = "Shipped", OrderDate =  DateTime.Parse("2025-10-17"), Amount = 853.90 },
                new OrdersTrackData { OrderID = "ORD1485", CustomerName = "Jane Smith", Product = "Shirt", Status = "Pending", OrderDate =  DateTime.Parse("2025-11-17"), Amount = 786.05 },
                new OrdersTrackData { OrderID = "ORD1486", CustomerName = "Eve Green", Product = "Bag", Status = "Shipped", OrderDate =  DateTime.Parse("2025-08-14"), Amount = 461.95 },
                new OrdersTrackData { OrderID = "ORD1487", CustomerName = "Carol Davis", Product = "Watch", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-03-23"), Amount = 875.68 },
                new OrdersTrackData { OrderID = "ORD1488", CustomerName = "Henry Taylor", Product = "Phone", Status = "Delivered", OrderDate =  DateTime.Parse("2025-02-12"), Amount = 378.13 },
                new OrdersTrackData { OrderID = "ORD1489", CustomerName = "Jane Smith", Product = "Tablet", Status = "Shipped", OrderDate =  DateTime.Parse("2025-12-25"), Amount = 757.68 },
                new OrdersTrackData { OrderID = "ORD1490", CustomerName = "Henry Taylor", Product = "Bag", Status = "Pending", OrderDate =  DateTime.Parse("2025-04-20"), Amount = 482.04 },
                new OrdersTrackData { OrderID = "ORD1491", CustomerName = "Kelly Gray", Product = "Headphone", Status = "Ready To Ship", OrderDate =  DateTime.Parse("2025-01-05"), Amount = 17.98 },
                new OrdersTrackData { OrderID = "ORD1492", CustomerName = "Grace Lee", Product = "Tablet", Status = "Delivered", OrderDate =  DateTime.Parse("2025-09-02"), Amount = 80.12 },
                new OrdersTrackData { OrderID = "ORD1493", CustomerName = "Henry Taylor", Product = "Bag", Status = "Pending", OrderDate =  DateTime.Parse("2025-06-10"), Amount = 373.89 },
                new OrdersTrackData { OrderID = "ORD1494", CustomerName = "Frank Miller", Product = "Tablet", Status = "Canceled", OrderDate =  DateTime.Parse("2025-11-25"), Amount = 993.01 },
                new OrdersTrackData { OrderID = "ORD1495", CustomerName = "Henry Taylor", Product = "Shoe", Status = "Pending", OrderDate =  DateTime.Parse("2025-11-09"), Amount = 653.52 },
                new OrdersTrackData { OrderID = "ORD1496", CustomerName = "Rose Pink", Product = "Headphone", Status = "Shipped", OrderDate =  DateTime.Parse("2025-07-30"), Amount = 619.92 },
                new OrdersTrackData { OrderID = "ORD1497", CustomerName = "Carol Davis", Product = "Bag", Status = "Pending", OrderDate =  DateTime.Parse("2025-03-13"), Amount = 754.92 },
                new OrdersTrackData { OrderID = "ORD1498", CustomerName = "Rose Pink", Product = "Tablet", Status = "Shipped", OrderDate =  DateTime.Parse("2025-03-13"), Amount = 255.31 },
                new OrdersTrackData { OrderID = "ORD1499", CustomerName = "David Brown", Product = "Shoe", Status = "In Transit", OrderDate =  DateTime.Parse("2025-12-20"), Amount = 36.56 }
            };
        }
    }
}