#region Copyright Syncfusion® Inc. 2001-2026.
// Copyright Syncfusion® Inc. 2001-2026. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EJ2CoreSampleBrowser.Models
{
    public class SupportData
    {
        public SupportData() { }

        public SupportData(string TicketID, string TypeOfRequest, string Category, string Title, string Description, string Rating, string Assignee, string Status, string Priority, DateTime CreatedDate, string CustomerEmail)
        {
            this.TicketID = TicketID;
            this.TypeOfRequest = TypeOfRequest;
            this.Category = Category;
            this.Title = Title;
            this.Description = Description;
            this.Rating = Rating;
            this.Assignee = Assignee;
            this.Status = Status;
            this.Priority = Priority;
            this.CreatedDate = CreatedDate;
            this.CustomerEmail = CustomerEmail;
        }

        public static List<SupportData> GetAllRecords()
        {
            return new List<SupportData>
            {
                new SupportData("TICKET-001", "Bug", "Product", "App Login Issue", "The app login is crashing frequently during use. Please investigate and provide a patch to stabilize it. This affects daily operations and needs urgent attention for smooth functionality.", "Neutral", "John Doe", "In Progress", "Medium", new DateTime(2025, 10, 26), "user1@test.com"),
                new SupportData("TICKET-002", "Subscription Cancellation", "Billing", "Cancel Monthly Plan", "Request to immediately cancel the monthly subscription due to billing discrepancies. Confirm no further charges and process any prorated refund if applicable. Follow up via email.", "Dissatisfied", "Sarah Lee", "Resolved", "Low", new DateTime(2025, 10, 25), "user2@service.com"),
                new SupportData("TICKET-003", "Feature Enhancement", "Product", "Add Dark Mode", "Suggest adding a dark mode option to the interface for better low-light usability. This would enhance user comfort during extended sessions and align with modern app standards.", "Very Satisfied", "Tom Wilson", "Closed", "Medium", new DateTime(2025, 10, 20), "user3@test.com"),
                new SupportData("TICKET-004", "Refund", "Support", "Process Full Refund", "Item received damaged upon delivery; requesting full refund and return label. Include photos as evidence. Ensure swift processing to maintain customer satisfaction.", "Neutral", "John Doe", "Resolved", "Urgent", new DateTime(2025, 10, 21), "user4@service.com"),
                new SupportData("TICKET-005", "Refund", "Support", "Return Defective Item", "Defective product failed within warranty period. Initiate return process and issue replacement or refund. Provide tracking details once shipped back.", "Neutral", "Sarah Lee", "In Progress", "Urgent", new DateTime(2025, 10, 21), "user5@test.com"),
                new SupportData("TICKET-006", "Onboarding Assistance", "Onboarding", "Guide New Setup", "New user struggling with initial account setup. Offer step-by-step guidance via chat or video. Clarify email verification and profile completion steps.", "Satisfied", "Mike Johnson", "Closed", "Low", new DateTime(2025, 10, 27), "user6@mail.com"),
                new SupportData("TICKET-007", "Bug", "Product", "Fix Search Glitch", "Search function returns irrelevant results consistently. Debug and optimize algorithm for accuracy. Test with various queries to verify improvements.", "Very Satisfied", "Sarah Lee", "In Progress", "Medium", new DateTime(2025, 11, 14), "user7@test.com"),
                new SupportData("TICKET-008", "Bug", "Product", "Dashboard Load Error", "Dashboard fails to load on mobile devices. Identify compatibility issues and deploy hotfix. Ensure cross-platform consistency for all users.", "Neutral", "Sarah Lee", "Open", "Medium", new DateTime(2025, 11, 18), "user8@domain.com"),
                new SupportData("TICKET-009", "Subscription Cancellation", "Billing", "End Annual Subscription", "Terminate annual plan effective immediately due to service changes. Verify no auto-renewal and confirm cancellation email. Process any outstanding credits.", "Very Dissatisfied", "Tom Wilson", "In Progress", "High", new DateTime(2025, 10, 25), "user9@service.com"),
                new SupportData("TICKET-010", "Technical Support", "Support", "Troubleshoot Connection Drop", "Frequent connection drops during sessions. Run diagnostics on network stability and suggest optimizations. Provide temporary workarounds if needed.", "Satisfied", "Mike Johnson", "Open", "Urgent", new DateTime(2025, 10, 30), "user10@service.com"),
                new SupportData("TICKET-011", "Bug", "Product", "Notification Delay Bug", "Notifications arrive hours late, impacting responsiveness. Prioritize queue processing enhancements to sync in real-time for better engagement.", "Very Satisfied", "Jane Smith", "In Progress", "Medium", new DateTime(2025, 11, 1), "user1@domain.com"),
                new SupportData("TICKET-012", "Feature Enhancement", "Product", "Implement Voice Search", "Introduce voice search capability for hands-free operation. Integrate speech recognition API and test for accuracy across accents and languages.", "Satisfied", "Tom Wilson", "Resolved", "Low", new DateTime(2025, 11, 13), "user2@test.com"),
                new SupportData("TICKET-013", "Refund", "Support", "Expedite Return Shipping", "Urgent return for faulty hardware; cover expedited shipping costs. Coordinate pickup and inspect upon receipt to prevent future occurrences.", "Neutral", "Jane Smith", "Closed", "Urgent", new DateTime(2025, 11, 4), "user3@domain.com"),
                new SupportData("TICKET-014", "Bug", "Product", "Profile Sync Failure", "Profile data not syncing across devices. Review cloud sync mechanism and reinforce data integrity checks to avoid loss.", "Neutral", "Jane Smith", "Closed", "Low", new DateTime(2025, 11, 5), "user4@test.com"),
                new SupportData("TICKET-015", "Technical Support", "Support", "API Integration Help", "Assistance needed with API key setup for third-party integration. Walk through authentication steps and troubleshoot common errors.", "Very Satisfied", "John Doe", "In Progress", "Urgent", new DateTime(2025, 10, 25), "user5@test.com"),
                new SupportData("TICKET-016", "Technical Support", "Support", "Reset Forgotten Password", "User locked out after multiple failed login attempts. Send secure reset link and advise on two-factor authentication enablement.", "Neutral", "John Doe", "Closed", "Urgent", new DateTime(2025, 10, 31), "user6@example.com"),
                new SupportData("TICKET-017", "Subscription Cancellation", "Billing", "Downgrade to Basic", "Switch from premium to basic plan mid-cycle. Prorate charges and update access levels without service interruption.", "Satisfied", "Tom Wilson", "Open", "Medium", new DateTime(2025, 11, 12), "user7@service.com"),
                new SupportData("TICKET-018", "Subscription Cancellation", "Billing", "Pause Recurring Billing", "Temporary pause on billing for three months due to financial constraints. Resume automatically afterward with notification.", "Neutral", "Mike Johnson", "In Progress", "Medium", new DateTime(2025, 11, 2), "user8@service.com"),
                new SupportData("TICKET-019", "Subscription Cancellation", "Billing", "Verify Cancellation Status", "Confirm if previous cancellation request was processed. If not, execute now and refund overcharged amounts promptly.", "Neutral", "Mike Johnson", "Open", "Low", new DateTime(2025, 10, 31), "user9@test.com"),
                new SupportData("TICKET-020", "Feature Enhancement", "Product", "Customize Notification Tones", "Allow users to select custom tones for different notification types. Boost personalization and reduce alert fatigue effectively.", "Very Satisfied", "Sarah Lee", "Resolved", "Medium", new DateTime(2025, 10, 28), "user10@service.com"),
                new SupportData("TICKET-021", "Technical Support", "Support", "Optimize Performance Lag", "App lags on older devices during peak usage. Profile and optimize resource consumption for smoother performance.", "Neutral", "Tom Wilson", "Resolved", "High", new DateTime(2025, 11, 8), "user1@example.com"),
                new SupportData("TICKET-022", "Onboarding Assistance", "Onboarding", "Clarify Feature Tour", "Onboarding tour skips key features; revise flow to include interactive demos. Improve retention through better initial guidance.", "Satisfied", "Tom Wilson", "Open", "Urgent", new DateTime(2025, 11, 15), "user2@example.com"),
                new SupportData("TICKET-023", "Technical Support", "Support", "Firewall Block Resolution", "Corporate firewall blocks app access; provide whitelist instructions and alternative ports if necessary for seamless connectivity.", "Satisfied", "Tom Wilson", "Open", "Medium", new DateTime(2025, 10, 28), "user3@mail.com"),
                new SupportData("TICKET-024", "Technical Support", "Support", "Data Export Format", "Export function outputs in incompatible CSV format. Convert to Excel compatibility and add date filtering options.", "Neutral", "Tom Wilson", "Closed", "Urgent", new DateTime(2025, 11, 4), "user4@service.com"),
                new SupportData("TICKET-025", "Subscription Cancellation", "Billing", "Refund Overcharge Dispute", "Billed twice for same period; dispute and refund excess amount. Review billing logs to prevent recurrence.", "Neutral", "Mike Johnson", "Open", "High", new DateTime(2025, 11, 8), "user5@service.com"),
                new SupportData("TICKET-026", "Feature Enhancement", "Product", "Batch Upload Support", "Enable batch file uploads for efficiency. Limit to 50 files max and validate formats upfront to avoid errors.", "Very Satisfied", "Emily Davis", "Resolved", "Medium", new DateTime(2025, 11, 12), "user6@test.com"),
                new SupportData("TICKET-027", "Onboarding Assistance", "Onboarding", "Team Invite Tutorial", "Struggling to invite team members; create dedicated tutorial video. Cover permissions and group management basics.", "Satisfied", "Jane Smith", "Open", "High", new DateTime(2025, 11, 8), "user7@domain.com"),
                new SupportData("TICKET-028", "Refund", "Support", "Wrong Item Shipped", "Received incorrect item variant; swap for correct one at no cost. Update inventory tracking to avoid mismatches.", "Neutral", "Sarah Lee", "Closed", "Medium", new DateTime(2025, 10, 21), "user8@example.com"),
                new SupportData("TICKET-029", "Refund", "Support", "Expedited Refund Approval", "Standard refund taking too long; escalate for 24-hour processing. Communicate status updates throughout the procedure.", "Neutral", "Mike Johnson", "In Progress", "Urgent", new DateTime(2025, 10, 30), "user9@domain.com"),
                new SupportData("TICKET-030", "Feature Enhancement", "Product", "Advanced Analytics Dashboard", "Expand analytics with predictive trends and custom reports. Integrate visualization tools for deeper insights and decision-making.", "Neutral", "John Doe", "In Progress", "High", new DateTime(2025, 10, 26), "user10@domain.com"),
                new SupportData("TICKET-031", "Bug", "Product", "Email Validation Bug", "Invalid emails pass validation; tighten regex and add real-time checks. Prevent spam registrations proactively.", "Satisfied", "John Doe", "In Progress", "Medium", new DateTime(2025, 10, 23), "user1@mail.com"),
                new SupportData("TICKET-032", "Onboarding Assistance", "Onboarding", "Custom Workflow Setup", "Help configure custom workflows for automation. Demo integration with existing tools and troubleshoot initial runs.", "Very Satisfied", "Sarah Lee", "In Progress", "Low", new DateTime(2025, 11, 17), "user2@service.com"),
                new SupportData("TICKET-033", "Refund", "Support", "Partial Refund Request", "Partial service unused; calculate prorated refund based on usage logs. Adjust future invoices accordingly.", "Neutral", "John Doe", "Closed", "Medium", new DateTime(2025, 11, 3), "user3@service.com"),
                new SupportData("TICKET-034", "Bug", "Product", "Calendar Sync Error", "Calendar events not syncing with external apps. Align protocols and add error logging for diagnostics.", "Neutral", "Jane Smith", "Open", "Urgent", new DateTime(2025, 10, 25), "user4@example.com"),
                new SupportData("TICKET-035", "Onboarding Assistance", "Onboarding", "API Key Generation", "Guide through API key creation and secure storage. Highlight best practices for revocation and rotation.", "Satisfied", "Jane Smith", "Resolved", "High", new DateTime(2025, 11, 16), "user5@test.com"),
                new SupportData("TICKET-036", "Technical Support", "Support", "SSL Certificate Renewal", "Upcoming SSL expiry causing warnings; assist with renewal process and verify site security post-update.", "Neutral", "Tom Wilson", "Closed", "Urgent", new DateTime(2025, 11, 7), "user6@test.com"),
                new SupportData("TICKET-037", "Subscription Cancellation", "Billing", "Billing Cycle Adjustment", "Shift billing cycle to align with fiscal year-end. Recalculate prorations and notify of changes.", "Neutral", "Emily Davis", "Resolved", "Medium", new DateTime(2025, 11, 15), "user7@test.com"),
                new SupportData("TICKET-038", "Technical Support", "Support", "Database Query Optimization", "Slow queries impacting load times; analyze and index tables for faster retrieval. Monitor post-optimization.", "Very Satisfied", "Mike Johnson", "Closed", "Urgent", new DateTime(2025, 11, 18), "user8@test.com"),
                new SupportData("TICKET-039", "Technical Support", "Support", "VPN Compatibility Check", "App incompatible with certain VPNs; test configurations and document supported providers for users.", "Satisfied", "Sarah Lee", "Closed", "Medium", new DateTime(2025, 11, 12), "user9@test.com"),
                new SupportData("TICKET-040", "Feature Enhancement", "Product", "Multi-Language Support", "Add support for additional languages to expand global reach. Prioritize translations for UI elements and error messages.", "Satisfied", "Tom Wilson", "Resolved", "Low", new DateTime(2025, 10, 28), "user10@test.com"),
                new SupportData("TICKET-041", "Subscription Cancellation", "Billing", "Group Subscription End", "Terminate group subscription and migrate individual accounts. Ensure data transfer without loss.", "Very Satisfied", "Emily Davis", "Closed", "High", new DateTime(2025, 10, 23), "user1@test.com"),
                new SupportData("TICKET-042", "Feature Enhancement", "Product", "Offline Mode Access", "Develop offline mode for core features to support remote work. Sync changes upon reconnection seamlessly.", "Neutral", "John Doe", "Closed", "Medium", new DateTime(2025, 11, 13), "user2@test.com"),
                new SupportData("TICKET-043", "Refund", "Support", "Subscription Overpayment", "Overpaid due to duplicate charge; credit account or refund via original method. Audit for patterns.", "Satisfied", "Sarah Lee", "In Progress", "Urgent", new DateTime(2025, 10, 27), "user3@test.com"),
                new SupportData("TICKET-044", "Subscription Cancellation", "Billing", "Immediate Account Closure", "Close account and delete all associated data per privacy policy. Confirm via secure channel.", "Neutral", "Sarah Lee", "Closed", "High", new DateTime(2025, 10, 19), "user4@test.com"),
                new SupportData("TICKET-045", "Bug", "Product", "Filter Malfunction", "Filters not applying correctly in search results. Recalibrate logic and add unit tests for reliability.", "Very Satisfied", "John Doe", "Resolved", "Medium", new DateTime(2025, 11, 1), "user5@test.com"),
                new SupportData("TICKET-046", "Onboarding Assistance", "Onboarding", "Payment Gateway Link", "Link external payment gateway during onboarding; resolve authentication hurdles and verify transactions.", "Neutral", "Mike Johnson", "Closed", "Low", new DateTime(2025, 10, 24), "user6@test.com"),
                new SupportData("TICKET-047", "Feature Enhancement", "Product", "AI-Powered Suggestions", "Incorporate AI for personalized content suggestions. Train model on user behavior while respecting privacy settings.", "Neutral", "Sarah Lee", "Open", "Medium", new DateTime(2025, 11, 14), "user7@test.com"),
                new SupportData("TICKET-048", "Subscription Cancellation", "Billing", "Trial Extension Denied", "Request for trial extension denied; reconsider based on feedback and offer alternative promotional access.", "Satisfied", "Emily Davis", "Resolved", "High", new DateTime(2025, 11, 3), "user8@test.com"),
                new SupportData("TICKET-049", "Refund", "Support", "Non-Delivery Compensation", "Order not delivered after tracking stopped; compensate with full refund and free re-shipment option.", "Neutral", "Sarah Lee", "Closed", "Urgent", new DateTime(2025, 10, 30), "user9@test.com"),
                new SupportData("TICKET-050", "Refund", "Quality Assurance Failure", "Support", "Product quality below standards; return approved with full refund. Enhance QA processes for future batches.", "Neutral", "Tom Wilson", "Closed", "Medium", new DateTime(2025-10-27),"user10@test.com"),
                new SupportData("TICKET-051", "Onboarding Assistance", "Onboarding", "Role Assignment Guide", "Assign roles to new team members; explain permissions hierarchy and audit access regularly.", "Very Satisfied", "Tom Wilson", "Closed", "High", new DateTime(2025, 11, 6), "user1@test.com"),
                new SupportData("TICKET-052", "Feature Enhancement", "Product", "Collaborative Editing Tool", "Enable real-time collaborative editing with version history. Prevent conflicts and track changes meticulously.", "Satisfied", "Jane Smith", "In Progress", "Medium", new DateTime(2025, 10, 24), "user2@test.com"),
                new SupportData("TICKET-053", "Subscription Cancellation", "Billing", "Pro-Rated Cancellation", "Cancel mid-term subscription with pro-rated refund. Transfer active projects to free tier gracefully.", "Neutral", "Sarah Lee", "Open", "Low", new DateTime(2025, 11, 1), "user3@test.com"),
                new SupportData("TICKET-054", "Feature Enhancement", "Product", "Export to PDF", "Add PDF export for reports with customizable templates. Ensure high-fidelity rendering and security features.", "Neutral", "Jane Smith", "Closed", "Urgent", new DateTime(2025, 10, 22), "user4@test.com"),
                new SupportData("TICKET-055", "Feature Enhancement", "Product", "Theme Customization Options", "Offer more theme customization for branding. Include color pickers and font selections for professional use.", "Satisfied", "Sarah Lee", "Open", "Medium", new DateTime(2025, 10, 22), "user5@test.com"),
                new SupportData("TICKET-056", "Bug", "Product", "Upload Size Limit", "File uploads exceed size limit unexpectedly. Increase threshold and add progress indicators for large files.", "Satisfied", "Sarah Lee", "Closed", "High", new DateTime(2025, 11, 9), "user6@test.com"),
                new SupportData("TICKET-057", "Subscription Cancellation", "Billing", "Enterprise Plan Review", "Review enterprise plan for cost savings; suggest downgrade or features to justify retention. Schedule call for discussion.", "Very Satisfied", "Sarah Lee", "Closed", "Urgent", new DateTime(2025, 11, 16), "user7@test.com"),
                new SupportData("TICKET-058", "Bug", "Product", "Tag Duplication Glitch", "Tags duplicate unintentionally during editing. Implement deduplication logic and user confirmation prompts.", "Very Satisfied", "Sarah Lee", "Closed", "High", new DateTime(2025, 10, 22), "user8@test.com"),
                new SupportData("TICKET-059", "Feature Enhancement", "Product", "Keyboard Shortcuts Menu", "Compile and display keyboard shortcuts in a help menu. Accelerate productivity for power users.", "Neutral", "Sarah Lee", "Resolved", "Medium", new DateTime(2025, 11, 7), "user9@test.com"),
                new SupportData("TICKET-060", "Feature Enhancement", "Product", "Auto-Save Drafts", "Implement auto-save for drafts to prevent data loss. Notify on unsaved changes before closing tabs.", "Neutral", "Tom Wilson", "Resolved", "Low", new DateTime(2025, 11, 4), "user10@test.com"),
                new SupportData("TICKET-061", "Onboarding Assistance", "Onboarding", "Integrate Third-Party Apps", "Assist with integrating third-party apps during onboarding. Verify API connections and resolve permission issues.", "Satisfied", "John Doe", "Resolved", "High", new DateTime(2025, 11, 13), "user1@test.com"),
                new SupportData("TICKET-062", "Subscription Cancellation", "Billing", "Unused Credits Refund", "Refund unused subscription credits upon cancellation. Calculate based on fair usage policy and credit account.", "Neutral", "Emily Davis", "Closed", "Medium", new DateTime(2025, 11, 18), "user2@test.com"),
                new SupportData("TICKET-063", "Subscription Cancellation", "Billing", "Seasonal Pause Request", "Pause subscription seasonally; resume on specified date. Maintain data access during pause period.", "Satisfied", "Mike Johnson", "Closed", "Urgent", new DateTime(2025, 11, 5), "user3@test.com"),
                new SupportData("TICKET-064", "Subscription Cancellation", "Billing", "Compliance Audit Cancellation", "Cancel due to compliance audit findings; provide export of all data before deactivation.", "Satisfied", "Sarah Lee", "Closed", "High", new DateTime(2025, 10, 25), "user4@test.com"),
                new SupportData("TICKET-065", "Subscription Cancellation", "Billing", "Migration to Competitor", "Switching providers; facilitate data migration and cancel without penalties. Offer retention incentives if possible.", "Neutral", "Mike Johnson", "Open", "Medium", new DateTime(2025, 11, 4), "user5@test.com"),
                new SupportData("TICKET-066", "Subscription Cancellation", "Billing", "Budget Cut Impact", "Budget cuts necessitate cancellation; explore scaled-down options to retain partial services.", "Very Satisfied", "Mike Johnson", "Open", "Urgent", new DateTime(2025, 11, 4), "user6@test.com"),
                new SupportData("TICKET-067", "Onboarding Assistance", "Onboarding", "Advanced Permissions Setup", "Configure advanced permissions for enterprise onboarding. Define roles and test access controls thoroughly.", "Neutral", "Jane Smith", "Resolved", "Low", new DateTime(2025, 11, 1), "user7@test.com"),
                new SupportData("TICKET-068", "Feature Enhancement", "Product", "Drag-and-Drop Interface", "Upgrade to drag-and-drop for file management. Simplify reorganization and preview enhancements.", "Very Satisfied", "Jane Smith", "Closed", "Medium", new DateTime(2025, 10, 30), "user8@test.com"),
                new SupportData("TICKET-069", "Bug", "Product", "Print Function Crash", "Print feature crashes on large documents. Optimize rendering and add pagination support.", "Satisfied", "Emily Davis", "In Progress", "High", new DateTime(2025, 10, 25), "user9@test.com"),
                new SupportData("TICKET-070", "Bug", "Product", "Bookmark Corruption", "Bookmarks corrupt after updates; implement backup and recovery protocols immediately.", "Neutral", "John Doe", "Resolved", "Urgent", new DateTime(2025, 11, 13), "user10@test.com"),
                new SupportData("TICKET-071", "Subscription Cancellation", "Billing", "Post-Trial Discontinuation", "Decline post-trial continuation; ensure clean data export and account archival.", "Neutral", "Emily Davis", "In Progress", "High", new DateTime(2025, 10, 19), "user1@test.com"),
                new SupportData("TICKET-072", "Subscription Cancellation", "Billing", "Volume Discount Review", "Review volume discount eligibility upon usage drop; adjust tier or cancel if under threshold.", "Very Satisfied", "Sarah Lee", "In Progress", "Low", new DateTime(2025, 10, 26), "user2@test.com"),
                new SupportData("TICKET-073", "Feature Enhancement", "Product", "Gesture Controls Addition", "Add gesture controls for mobile navigation. Enhance intuitiveness and accessibility for touch interfaces.", "Satisfied", "Tom Wilson", "Resolved", "Medium", new DateTime(2025, 10, 24), "user3@test.com"),
                new SupportData("TICKET-074", "Subscription Cancellation", "Billing", "Merger-Related Cleanup", "Consolidate accounts post-merger; cancel duplicates and merge histories without data loss.", "Satisfied", "Emily Davis", "Open", "High", new DateTime(2025, 11, 2), "user4@test.com"),
                new SupportData("TICKET-075", "Technical Support", "Support", "Custom Domain Mapping", "Map custom domain to service; configure DNS records and SSL for secure access.", "Neutral", "Emily Davis", "In Progress", "Medium", new DateTime(2025, 11, 4), "user5@test.com"),
                new SupportData("TICKET-076", "Subscription Cancellation", "Billing", "Non-Renewal Confirmation", "Confirm non-renewal for upcoming cycle; send reminder and offer last-minute retention deals.", "Neutral", "Jane Smith", "Resolved", "Urgent", new DateTime(2025, 10, 23), "user6@test.com"),
                new SupportData("TICKET-077", "Technical Support", "Support", "Webhook Configuration Aid", "Configure webhooks for event notifications; test endpoints and handle authentication securely.", "Satisfied", "Tom Wilson", "Closed", "High", new DateTime(2025, 10, 25), "user7@test.com"),
                new SupportData("TICKET-078", "Technical Support", "Support", "Load Balancer Tuning", "Tune load balancer for traffic spikes; monitor metrics and scale resources dynamically.", "Neutral", "Tom Wilson", "Closed", "Urgent", new DateTime(2025, 10, 21), "user8@test.com"),
                new SupportData("TICKET-079", "Bug", "Product", "Validation Rule Bypass", "Validation rules bypassed in bulk imports; enforce checks and rollback invalid entries.", "Neutral", "Jane Smith", "Resolved", "Medium", new DateTime(2025, 10, 25), "user9@test.com"),
                new SupportData("TICKET-080", "Technical Support", "Support", "SAML Authentication Setup", "Set up SAML for single sign-on; integrate with identity provider and test federated login.", "Very Satisfied", "Jane Smith", "Resolved", "Low", new DateTime(2025, 11, 9), "user10@test.com"),
                new SupportData("TICKET-081", "Onboarding Assistance", "Onboarding", "Compliance Training Module", "Incorporate compliance training in onboarding; track completion and issue certificates upon finish.", "Dissatisfied", "Tom Wilson", "Open", "High", new DateTime(2025, 11, 10), "user1@test.com"),
                new SupportData("TICKET-082", "Subscription Cancellation", "Billing", "Legacy Plan Phaseout", "Phase out legacy plan; migrate to current tier with equivalent features and no cost increase.", "Satisfied", "Tom Wilson", "In Progress", "Medium", new DateTime(2025, 11, 6), "user2@test.com"),
                new SupportData("TICKET-083", "Technical Support", "Support", "Custom Script Debugging", "Debug custom scripts failing in production; review logs and suggest optimizations for stability.", "Satisfied", "Emily Davis", "Closed", "Urgent", new DateTime(2025, 11, 16), "user3@test.com"),
                new SupportData("TICKET-084", "Feature Enhancement", "Product", "QR Code Scanner", "Integrate QR code scanner for quick logins. Support offline scanning and secure token validation.", "Neutral", "Emily Davis", "Open", "Medium", new DateTime(2025, 11, 2), "user4@test.com"),
                new SupportData("TICKET-085", "Technical Support", "Support", "Backup Restoration Guide", "Guide through backup restoration after accidental deletion. Verify integrity and minimize downtime.", "Satisfied", "Sarah Lee", "In Progress", "Urgent", new DateTime(2025, 11, 18), "user5@test.com"),
                new SupportData("TICKET-086", "Onboarding Assistance", "Onboarding", "Webhook Endpoint Test", "Test webhook endpoints during onboarding; simulate events and validate payloads received correctly.", "Neutral", "Sarah Lee", "Open", "Low", new DateTime(2025, 11, 13), "user6@test.com"),
                new SupportData("TICKET-087", "Bug", "Product", "Pagination Overflow", "Pagination breaks on results exceeding limits; cap displays and add load-more functionality.", "Very Satisfied", "Sarah Lee", "Resolved", "Medium", new DateTime(2025, 10, 24), "user7@example.com"),
                new SupportData("TICKET-088", "Feature Enhancement", "Product", "Voice Memo Transcription", "Transcribe voice memos automatically using AI. Support multiple languages and edit transcripts inline.", "Neutral", "Tom Wilson", "Open", "High", new DateTime(2025, 10, 31), "user8@test.com"),
                new SupportData("TICKET-089", "Subscription Cancellation", "Billing", "Add-On Removal", "Remove unused add-ons from subscription; recalculate costs and confirm adjustments in next invoice.", "Neutral", "Tom Wilson", "Closed", "Medium", new DateTime(2025, 10, 22), "user9@test.com"),
                new SupportData("TICKET-090", "Technical Support", "Support", "OAuth Token Refresh", "OAuth tokens expire prematurely; automate refresh cycles and handle failures gracefully.", "Satisfied", "Mike Johnson", "Resolved", "Urgent", new DateTime(2025, 11, 10), "user10@test.com"),
                new SupportData("TICKET-091", "Bug", "Product", "Share Link Expiry", "Share links expire too soon; extend duration options and notify sharers of access logs.", "Satisfied", "Emily Davis", "In Progress", "Low", new DateTime(2025, 11, 12), "user1@test.com"),
                new SupportData("TICKET-092", "Bug", "Product", "Autocomplete Failure", "Autocomplete suggests incorrect entries; refine algorithm with user feedback loops for accuracy.", "Very Dissatisfied", "Emily Davis", "Resolved", "Medium", new DateTime(2025, 11, 4), "user2@test.com"),
                new SupportData("TICKET-093", "Onboarding Assistance", "Onboarding", "Metrics Dashboard Tour", "Tour new metrics dashboard; explain KPIs and customization for informed decision-making.", "Very Satisfied", "Sarah Lee", "In Progress", "High", new DateTime(2025, 11, 10), "user3@test.com"),
                new SupportData("TICKET-094", "Technical Support", "Support", "Log File Analysis", "Analyze server logs for anomaly patterns; recommend monitoring alerts for proactive issue detection.", "Neutral", "Tom Wilson", "Closed", "Medium", new DateTime(2025, 11, 3), "user4@test.com"),
                new SupportData("TICKET-095", "Onboarding Assistance", "Onboarding", "Custom Field Creation", "Create custom fields for data tracking; demonstrate usage in reports and filters.", "Satisfied", "Sarah Lee", "In Progress", "Low", new DateTime(2025, 10, 31), "user5@test.com"),
                new SupportData("TICKET-096", "Onboarding Assistance", "Onboarding", "Audit Log Review", "Review audit logs for compliance; set up alerts for suspicious activities and access changes.", "Neutral", "John Doe", "Closed", "Urgent", new DateTime(2025, 10, 31), "user6@test.com"),
                new SupportData("TICKET-097", "Technical Support", "Support", "Rate Limiting Bypass", "Rate limits bypassed by scripts; strengthen enforcement and add CAPTCHA for suspicious traffic.", "Neutral", "John Doe", "Open", "High", new DateTime(2025, 10, 26), "user7@test.com"),
                new SupportData("TICKET-098", "Onboarding Assistance", "Onboarding", "Workflow Automation Basics", "Basics of workflow automation; build simple triggers and actions with example templates.", "Very Satisfied", "Tom Wilson", "Resolved", "Medium", new DateTime(2025, 10, 31), "user8@test.com"),
                new SupportData("TICKET-099", "Feature Enhancement", "Product", "Embeddable Widgets", "Develop embeddable widgets for websites; ensure responsive design and secure data sharing.", "Neutral", "Emily Davis", "In Progress", "Urgent", new DateTime(2025, 11, 15), "user9@test.com"),
                new SupportData("TICKET-100", "Onboarding Assistance", "Onboarding", "Security Best Practices", "Outline security best practices in onboarding; cover password policies and phishing awareness training.", "Satisfied", "Tom Wilson", "Resolved", "Medium", new DateTime(2025, 11, 9), "user10@test.com"),
                new SupportData("TICKET-101", "Bug", "Support", "Resolve Support Bug", "A critical bug has been identified in the support module. Investigate root cause and apply a fix to restore normal functionality promptly.", "Satisfied", "Tom Wilson", "In Progress", "Urgent", new DateTime(2025, 11, 3), "user101@example.com"),
                new SupportData("TICKET-102", "Refund", "Billing", "Handle Billing Refund Request", "Customer requested a refund related to billing. Validate transaction details and process refund according to policy.", "Neutral", "Emily Davis", "In Progress", "Medium", new DateTime(2025, 11, 7), "user102@example.com"),
                new SupportData("TICKET-103", "Subscription Cancellation", "Support", "Cancel Support Subscription", "Customer requested cancellation of subscription under support. Ensure proper termination and confirm via email.", "Very Satisfied", "Tom Wilson", "Closed", "Low", new DateTime(2025, 11, 5), "user103@example.com"),
                new SupportData("TICKET-104", "Refund", "Product", "Handle Product Refund Request", "Customer requested a refund related to product. Validate transaction details and process refund according to policy.", "Satisfied", "Sarah Lee", "Closed", "Medium", new DateTime(2025, 11, 17), "user104@example.com"),
                new SupportData("TICKET-105", "Subscription Cancellation", "Onboarding", "Cancel Onboarding Subscription", "Customer requested cancellation of subscription under onboarding. Ensure proper termination and confirm via email.", "Very Satisfied", "Jane Smith", "Open", "Medium", new DateTime(2025, 10, 20), "user105@example.com"),
                new SupportData("TICKET-106", "Bug", "Onboarding", "Resolve Onboarding Bug", "A critical bug has been identified in the onboarding module. Investigate root cause and apply a fix to restore normal functionality promptly.", "Satisfied", "Mike Johnson", "Closed", "Low", new DateTime(2025, 10, 29), "user106@example.com"),
                new SupportData("TICKET-107", "Feature Enhancement", "Product", "Enhance Product Features", "Customer suggested improvements for product functionality. Review feasibility and plan implementation for better user experience.", "Very Satisfied", "John Doe", "Closed", "Medium", new DateTime(2025, 11, 15), "user107@example.com"),
                new SupportData("TICKET-108", "Technical Support", "Onboarding", "Provide Onboarding Technical Assistance", "Customer needs Technical Support for onboarding. Diagnose the issue and guide them through resolution steps.", "Neutral", "Mike Johnson", "Closed", "Low", new DateTime(2025, 10, 27), "user108@example.com"),
                new SupportData("TICKET-109", "Subscription Cancellation", "Billing", "Cancel Billing Subscription", "Customer requested cancellation of subscription under billing. Ensure proper termination and confirm via email.", "Neutral", "Sarah Lee", "Open", "High", new DateTime(2025, 11, 13), "user109@example.com"),
                new SupportData("TICKET-110", "Bug", "Support", "Resolve Support Bug", "A critical bug has been identified in the support module. Investigate root cause and apply a fix to restore normal functionality promptly.", "Neutral", "Sarah Lee", "Closed", "High", new DateTime(2025, 11, 17), "user110@example.com"),
                new SupportData("TICKET-111", "Refund", "Support", "Handle Support Refund Request", "Customer requested a refund related to support. Validate transaction details and process refund according to policy.", "Neutral", "John Doe", "In Progress", "Low", new DateTime(2025, 11, 8), "user111@example.com"),
                new SupportData("TICKET-112", "Subscription Cancellation", "Product", "Cancel Product Subscription", "Customer requested cancellation of subscription under product. Ensure proper termination and confirm via email.", "Neutral", "Sarah Lee", "Closed", "High", new DateTime(2025, 11, 8), "user112@example.com"),
                new SupportData("TICKET-113", "Bug", "Onboarding", "Resolve Onboarding Bug", "A critical bug has been identified in the onboarding module. Investigate root cause and apply a fix to restore normal functionality promptly.", "Neutral", "John Doe", "Closed", "Medium", new DateTime(2025, 11, 8), "user113@example.com"),
                new SupportData("TICKET-114", "Feature Enhancement", "Support", "Enhance Support Features", "Customer suggested improvements for support functionality. Review feasibility and plan implementation for better user experience.", "Very Satisfied", "Tom Wilson", "In Progress", "Urgent", new DateTime(2025, 10, 27), "user114@example.com"),
                new SupportData("TICKET-115", "Onboarding Assistance", "Support", "Assist with Support Onboarding", "Customer requires help during onboarding for support. Offer detailed instructions and ensure smooth setup.", "Very Satisfied", "Jane Smith", "In Progress", "Medium", new DateTime(2025, 11, 2), "user115@example.com"),
                new SupportData("TICKET-116", "Feature Enhancement", "Onboarding", "Enhance Onboarding Features", "Customer suggested improvements for onboarding functionality. Review feasibility and plan implementation for better user experience.", "Satisfied", "Emily Davis", "Resolved", "Urgent", new DateTime(2025, 11, 17), "user116@example.com"),
                new SupportData("TICKET-117", "Subscription Cancellation", "Billing", "Cancel Billing Subscription", "Customer requested cancellation of subscription under billing. Ensure proper termination and confirm via email.", "Satisfied", "Emily Davis", "Closed", "High", new DateTime(2025, 11, 13), "user117@example.com"),
                new SupportData("TICKET-118", "Technical Support", "Product", "Provide Product Technical Assistance", "Customer needs Technical Support for product. Diagnose the issue and guide them through resolution steps.", "Satisfied", "Mike Johnson", "In Progress", "High", new DateTime(2025, 11, 6), "user118@example.com"),
                new SupportData("TICKET-119", "Subscription Cancellation", "Support", "Cancel Support Subscription", "Customer requested cancellation of subscription under support. Ensure proper termination and confirm via email.", "Neutral", "Jane Smith", "Open", "Medium", new DateTime(2025, 10, 20), "user119@example.com"),
                new SupportData("TICKET-120", "Technical Support", "Support", "Provide Support Technical Assistance", "Customer needs Technical Support for support. Diagnose the issue and guide them through resolution steps.", "Neutral", "Sarah Lee", "Closed", "Low", new DateTime(2025, 11, 2), "user120@example.com"),
                new SupportData("TICKET-121", "Bug", "Support", "Resolve Support Bug", "A critical bug has been identified in the support module. Investigate root cause and apply a fix to restore normal functionality promptly.", "Neutral", "Jane Smith", "Resolved", "Low", new DateTime(2025, 11, 9), "user121@example.com"),
                new SupportData("TICKET-122", "Onboarding Assistance", "Product", "Assist with Product Onboarding", "Customer requires help during onboarding for product. Offer detailed instructions and ensure smooth setup.", "Neutral", "Mike Johnson", "Open", "Medium", new DateTime(2025, 11, 6), "user122@example.com"),
                new SupportData("TICKET-123", "Onboarding Assistance", "Billing", "Assist with Billing Onboarding", "Customer requires help during onboarding for billing. Offer detailed instructions and ensure smooth setup.", "Neutral", "Mike Johnson", "Resolved", "Urgent", new DateTime(2025, 11, 7), "user123@example.com"),
                new SupportData("TICKET-124", "Refund", "Onboarding", "Handle Onboarding Refund Request", "Customer requested a refund related to onboarding. Validate transaction details and process refund according to policy.", "Satisfied", "Jane Smith", "Resolved", "Medium", new DateTime(2025, 11, 16), "user124@example.com"),
                new SupportData("TICKET-125", "Subscription Cancellation", "Billing", "Cancel Billing Subscription", "Customer requested cancellation of subscription under billing. Ensure proper termination and confirm via email.", "Satisfied", "Tom Wilson", "Closed", "Medium", new DateTime(2025, 10, 19), "user125@example.com"),
                new SupportData("TICKET-126", "Subscription Cancellation", "Onboarding", "Cancel Onboarding Subscription", "Customer requested cancellation of subscription under onboarding. Ensure proper termination and confirm via email.", "Very Satisfied", "John Doe", "Closed", "Medium", new DateTime(2025, 11, 11), "user126@example.com"),
                new SupportData("TICKET-127", "Onboarding Assistance", "Billing", "Assist with Billing Onboarding", "Customer requires help during onboarding for billing. Offer detailed instructions and ensure smooth setup.", "Neutral", "Emily Davis", "Open", "Urgent", new DateTime(2025, 10, 21), "user127@example.com"),
                new SupportData("TICKET-128", "Refund", "Onboarding", "Handle Onboarding Refund Request", "Customer requested a refund related to onboarding. Validate transaction details and process refund according to policy.", "Very Satisfied", "Sarah Lee", "Resolved", "High", new DateTime(2025, 11, 2), "user128@example.com"),
                new SupportData("TICKET-129", "Technical Support", "Billing", "Provide Billing Technical Assistance", "Customer needs Technical Support for billing. Diagnose the issue and guide them through resolution steps.", "Neutral", "John Doe", "Open", "Medium", new DateTime(2025, 11, 10), "user129@example.com"),
                new SupportData("TICKET-130", "Feature Enhancement", "Product", "Enhance Product Features", "Customer suggested improvements for product functionality. Review feasibility and plan implementation for better user experience.", "Neutral", "Tom Wilson", "Open", "Medium", new DateTime(2025, 11, 12), "user130@example.com"),
                new SupportData("TICKET-131", "Technical Support", "Support", "Provide Support Technical Assistance", "Customer needs Technical Support for support. Diagnose the issue and guide them through resolution steps.", "Neutral", "John Doe", "Open", "High", new DateTime(2025, 11, 2), "user131@example.com"),
                new SupportData("TICKET-132", "Onboarding Assistance", "Onboarding", "Assist with Onboarding Onboarding", "Customer requires help during onboarding for onboarding. Offer detailed instructions and ensure smooth setup.", "Very Satisfied", "Jane Smith", "Resolved", "Medium", new DateTime(2025, 11, 13), "user132@example.com"),
                new SupportData("TICKET-133", "Technical Support", "Billing", "Provide Billing Technical Assistance", "Customer needs Technical Support for billing. Diagnose the issue and guide them through resolution steps.", "Very Satisfied", "John Doe", "Closed", "Low", new DateTime(2025, 10, 28), "user133@example.com"),
                new SupportData("TICKET-134", "Refund", "Billing", "Handle Billing Refund Request", "Customer requested a refund related to billing. Validate transaction details and process refund according to policy.", "Very Satisfied", "John Doe", "Resolved", "High", new DateTime(2025, 10, 31), "user134@example.com"),
                new SupportData("TICKET-135", "Refund", "Support", "Handle Support Refund Request", "Customer requested a refund related to support. Validate transaction details and process refund according to policy.", "Neutral", "John Doe", "Resolved", "High", new DateTime(2025, 10, 27), "user135@example.com"),
                new SupportData("TICKET-136", "Onboarding Assistance", "Billing", "Assist with Billing Onboarding", "Customer requires help during onboarding for billing. Offer detailed instructions and ensure smooth setup.", "Neutral", "Jane Smith", "Closed", "Medium", new DateTime(2025, 11, 8), "user136@example.com"),
                new SupportData("TICKET-137", "Onboarding Assistance", "Billing", "Assist with Billing Onboarding", "Customer requires help during onboarding for billing. Offer detailed instructions and ensure smooth setup.", "Very Satisfied", "Tom Wilson", "Closed", "Urgent", new DateTime(2025, 11, 18), "user137@example.com"),
                new SupportData("TICKET-138", "Refund", "Onboarding", "Handle Onboarding Refund Request", "Customer requested a refund related to onboarding. Validate transaction details and process refund according to policy.", "Very Satisfied", "Emily Davis", "Closed", "Low", new DateTime(2025, 10, 31), "user138@example.com"),
                new SupportData("TICKET-139", "Subscription Cancellation", "Billing", "Cancel Billing Subscription", "Customer requested cancellation of subscription under billing. Ensure proper termination and confirm via email.", "Very Satisfied", "Emily Davis", "Closed", "Low", new DateTime(2025, 10, 21), "user139@example.com"),
                new SupportData("TICKET-140", "Subscription Cancellation", "Onboarding", "Cancel Onboarding Subscription", "Customer requested cancellation of subscription under onboarding. Ensure proper termination and confirm via email.", "Neutral", "Emily Davis", "Resolved", "Low", new DateTime(2025, 10, 27), "user140@example.com"),
                new SupportData("TICKET-141", "Onboarding Assistance", "Support", "Assist with Support Onboarding", "Customer requires help during onboarding for support. Offer detailed instructions and ensure smooth setup.", "Satisfied", "Mike Johnson", "Closed", "Medium", new DateTime(2025, 10, 23), "user141@example.com"),
                new SupportData("TICKET-142", "Subscription Cancellation", "Product", "Cancel Product Subscription", "Customer requested cancellation of subscription under product. Ensure proper termination and confirm via email.", "Neutral", "John Doe", "Closed", "Low", new DateTime(2025, 11, 18), "user142@example.com"),
                new SupportData("TICKET-143", "Subscription Cancellation", "Product", "Cancel Product Subscription", "Customer requested cancellation of subscription under product. Ensure proper termination and confirm via email.", "Very Satisfied", "Emily Davis", "Open", "High", new DateTime(2025, 10, 21), "user143@example.com"),
                new SupportData("TICKET-144", "Subscription Cancellation", "Support", "Cancel Support Subscription", "Customer requested cancellation of subscription under support. Ensure proper termination and confirm via email.", "Neutral", "Mike Johnson", "Open", "Medium", new DateTime(2025, 11, 15), "user144@example.com"),
                new SupportData("TICKET-145", "Technical Support", "Product", "Provide Product Technical Assistance", "Customer needs Technical Support for product. Diagnose the issue and guide them through resolution steps.", "Satisfied", "Tom Wilson", "Closed", "Medium", new DateTime(2025, 11, 13), "user145@example.com"),
                new SupportData("TICKET-146", "Bug", "Billing", "Resolve Billing Bug", "A critical bug has been identified in the billing module. Investigate root cause and apply a fix to restore normal functionality promptly.", "Very Satisfied", "Tom Wilson", "Open", "Urgent", new DateTime(2025, 11, 3), "user146@example.com"),
                new SupportData("TICKET-147", "Technical Support", "Product", "Provide Product Technical Assistance", "Customer needs Technical Support for product. Diagnose the issue and guide them through resolution steps.", "Satisfied", "Jane Smith", "Resolved", "Medium", new DateTime(2025, 11, 10), "user147@example.com"),
                new SupportData("TICKET-148", "Technical Support", "Support", "Provide Support Technical Assistance", "Customer needs Technical Support for support. Diagnose the issue and guide them through resolution steps.", "Neutral", "Sarah Lee", "Resolved", "Urgent", new DateTime(2025, 11, 14), "user148@example.com"),
                new SupportData("TICKET-149", "Feature Enhancement", "Billing", "Enhance Billing Features", "Customer suggested improvements for billing functionality. Review feasibility and plan implementation for better user experience.", "Satisfied", "Jane Smith", "In Progress", "Medium", new DateTime(2025, 10, 24), "user149@example.com"),
                new SupportData("TICKET-150", "Technical Support", "Product", "Provide Product Technical Assistance", "Customer needs Technical Support for product. Diagnose the issue and guide them through resolution steps.", "Satisfied", "Mike Johnson", "Open", "Low", new DateTime(2025, 10, 22), "user150@example.com"),
                new SupportData("TICKET-151", "Refund", "Billing", "Handle Billing Refund Request", "Customer requested a refund related to billing. Validate transaction details and process refund according to policy.", "Very Satisfied", "Jane Smith", "Resolved", "Urgent", new DateTime(2025, 11, 18), "user151@example.com"),
                new SupportData("TICKET-152", "Bug", "Onboarding", "Resolve Onboarding Bug", "A critical bug has been identified in the onboarding module. Investigate root cause and apply a fix to restore normal functionality promptly.", "Satisfied", "Mike Johnson", "In Progress", "Urgent", new DateTime(2025, 10, 28), "user152@example.com"),
                new SupportData("TICKET-153", "Refund", "Billing", "Handle Billing Refund Request", "Customer requested a refund related to billing. Validate transaction details and process refund according to policy.", "Neutral", "Emily Davis", "In Progress", "Urgent", new DateTime(2025, 11, 8), "user153@example.com"),
                new SupportData("TICKET-154", "Subscription Cancellation", "Product", "Cancel Product Subscription", "Customer requested cancellation of subscription under product. Ensure proper termination and confirm via email.", "Very Satisfied", "Mike Johnson", "Resolved", "Low", new DateTime(2025, 10, 24), "user154@example.com"),
                new SupportData("TICKET-155", "Refund", "Support", "Handle Support Refund Request", "Customer requested a refund related to support. Validate transaction details and process refund according to policy.", "Satisfied", "Mike Johnson", "Closed", "Medium", new DateTime(2025, 11, 16), "user155@example.com"),
                new SupportData("TICKET-156", "Refund", "Onboarding", "Handle Onboarding Refund Request", "Customer requested a refund related to onboarding. Validate transaction details and process refund according to policy.", "Neutral", "John Doe", "Resolved", "Low", new DateTime(2025, 11, 18), "user156@example.com"),
                new SupportData("TICKET-157", "Subscription Cancellation", "Support", "Cancel Support Subscription", "Customer requested cancellation of subscription under support. Ensure proper termination and confirm via email.", "Satisfied", "Tom Wilson", "In Progress", "Medium", new DateTime(2025, 11, 7), "user157@example.com"),
                new SupportData("TICKET-158", "Onboarding Assistance", "Onboarding", "Assist with Onboarding Onboarding", "Customer requires help during onboarding for onboarding. Offer detailed instructions and ensure smooth setup.", "Satisfied", "John Doe", "In Progress", "Urgent", new DateTime(2025, 11, 12), "user158@example.com"),
                new SupportData("TICKET-159", "Subscription Cancellation", "Product", "Cancel Product Subscription", "Customer requested cancellation of subscription under product. Ensure proper termination and confirm via email.", "Satisfied", "John Doe", "Closed", "Urgent", new DateTime(2025, 11, 5), "user159@example.com"),
                new SupportData("TICKET-160", "Refund", "Support", "Handle Support Refund Request", "Customer requested a refund related to support. Validate transaction details and process refund according to policy.", "Neutral", "Jane Smith", "In Progress", "Urgent", new DateTime(2025, 11, 10), "user160@example.com"),
                new SupportData("TICKET-161", "Bug", "Billing", "Resolve Billing Bug", "A critical bug has been identified in the billing module. Investigate root cause and apply a fix to restore normal functionality promptly.", "Very Satisfied", "Mike Johnson", "Resolved", "Urgent", new DateTime(2025, 10, 20), "user161@example.com"),
                new SupportData("TICKET-162", "Onboarding Assistance", "Support", "Assist with Support Onboarding", "Customer requires help during onboarding for support. Offer detailed instructions and ensure smooth setup.", "Satisfied", "John Doe", "In Progress", "High", new DateTime(2025, 10, 29), "user162@example.com"),
                new SupportData("TICKET-163", "Feature Enhancement", "Support", "Enhance Support Features", "Customer suggested improvements for support functionality. Review feasibility and plan implementation for better user experience.", "Neutral", "Emily Davis", "Open", "Urgent", new DateTime(2025, 11, 2), "user163@example.com"),
                new SupportData("TICKET-164", "Bug", "Onboarding", "Resolve Onboarding Bug", "A critical bug has been identified in the onboarding module. Investigate root cause and apply a fix to restore normal functionality promptly.", "Satisfied", "Tom Wilson", "Closed", "Urgent", new DateTime(2025, 10, 27), "user164@example.com"),
                new SupportData("TICKET-165", "Onboarding Assistance", "Billing", "Assist with Billing Onboarding", "Customer requires help during onboarding for billing. Offer detailed instructions and ensure smooth setup.", "Satisfied", "Mike Johnson", "In Progress", "High", new DateTime(2025, 11, 8), "user165@example.com"),
                new SupportData("TICKET-166", "Refund", "Product", "Handle Product Refund Request", "Customer requested a refund related to product. Validate transaction details and process refund according to policy.", "Satisfied", "Mike Johnson", "Closed", "Medium", new DateTime(2025, 11, 2), "user166@example.com"),
                new SupportData("TICKET-167", "Feature Enhancement", "Billing", "Enhance Billing Features", "Customer suggested improvements for billing functionality. Review feasibility and plan implementation for better user experience.", "Neutral", "Jane Smith", "Resolved", "Medium", new DateTime(2025, 11, 18), "user167@example.com"),
                new SupportData("TICKET-168", "Onboarding Assistance", "Product", "Assist with Product Onboarding", "Customer requires help during onboarding for product. Offer detailed instructions and ensure smooth setup.", "Satisfied", "Jane Smith", "Resolved", "Medium", new DateTime(2025, 11, 9), "user168@example.com"),
                new SupportData("TICKET-169", "Refund", "Onboarding", "Handle Onboarding Refund Request", "Customer requested a refund related to onboarding. Validate transaction details and process refund according to policy.", "Satisfied", "Tom Wilson", "In Progress", "Urgent", new DateTime(2025, 11, 18), "user169@example.com"),
                new SupportData("TICKET-170", "Feature Enhancement", "Product", "Enhance Product Features", "Customer suggested improvements for product functionality. Review feasibility and plan implementation for better user experience.", "Neutral", "Sarah Lee", "Resolved", "High", new DateTime(2025, 11, 11), "user170@example.com"),
                new SupportData("TICKET-171", "Bug", "Billing", "Resolve Billing Bug", "A critical bug has been identified in the billing module. Investigate root cause and apply a fix to restore normal functionality promptly.", "Satisfied", "Tom Wilson", "In Progress", "Urgent", new DateTime(2025, 10, 21), "user171@example.com"),
                new SupportData("TICKET-172", "Bug", "Product", "Resolve Product Bug", "A critical bug has been identified in the product module. Investigate root cause and apply a fix to restore normal functionality promptly.", "Very Satisfied", "Sarah Lee", "Resolved", "Medium", new DateTime(2025, 11, 15), "user172@example.com"),
                new SupportData("TICKET-173", "Subscription Cancellation", "Product", "Cancel Product Subscription", "Customer requested cancellation of subscription under product. Ensure proper termination and confirm via email.", "Neutral", "Tom Wilson", "Closed", "High", new DateTime(2025, 11, 17), "user173@example.com"),
                new SupportData("TICKET-174", "Technical Support", "Product", "Provide Product Technical Assistance", "Customer needs Technical Support for product. Diagnose the issue and guide them through resolution steps.", "Very Satisfied", "Emily Davis", "Closed", "High", new DateTime(2025, 10, 22), "user174@example.com"),
                new SupportData("TICKET-175", "Bug", "Support", "Resolve Support Bug", "A critical bug has been identified in the support module. Investigate root cause and apply a fix to restore normal functionality promptly.", "Neutral", "Sarah Lee", "Closed", "Low", new DateTime(2025, 11, 18), "user175@example.com"),
                new SupportData("TICKET-176", "Subscription Cancellation", "Billing", "Cancel Billing Subscription", "Customer requested cancellation of subscription under billing. Ensure proper termination and confirm via email.", "Satisfied", "Mike Johnson", "Resolved", "Low", new DateTime(2025, 11, 17), "user176@example.com"),
                new SupportData("TICKET-177", "Subscription Cancellation", "Onboarding", "Cancel Onboarding Subscription", "Customer requested cancellation of subscription under onboarding. Ensure proper termination and confirm via email.", "Satisfied", "John Doe", "In Progress", "High", new DateTime(2025, 11, 11), "user177@example.com"),
                new SupportData("TICKET-178", "Technical Support", "Product", "Provide Product Technical Assistance", "Customer needs Technical Support for product. Diagnose the issue and guide them through resolution steps.", "Satisfied", "Sarah Lee", "Open", "Medium", new DateTime(2025, 11, 18), "user178@example.com"),
                new SupportData("TICKET-179", "Refund", "Product", "Handle Product Refund Request", "Customer requested a refund related to product. Validate transaction details and process refund according to policy.", "Neutral", "Jane Smith", "Open", "Low", new DateTime(2025, 11, 3), "user179@example.com"),
                new SupportData("TICKET-180", "Refund", "Support", "Handle Support Refund Request", "Customer requested a refund related to support. Validate transaction details and process refund according to policy.", "Satisfied", "Emily Davis", "In Progress", "Urgent", new DateTime(2025, 11, 4), "user180@example.com"),
                new SupportData("TICKET-181", "Refund", "Support", "Handle Support Refund Request", "Customer requested a refund related to support. Validate transaction details and process refund according to policy.", "Satisfied", "Emily Davis", "Open", "High", new DateTime(2025, 10, 29), "user181@example.com"),
                new SupportData("TICKET-182", "Feature Enhancement", "Onboarding", "Enhance Onboarding Features", "Customer suggested improvements for onboarding functionality. Review feasibility and plan implementation for better user experience.", "Satisfied", "Sarah Lee", "In Progress", "High", new DateTime(2025, 11, 5), "user182@example.com"),
                new SupportData("TICKET-183", "Onboarding Assistance", "Billing", "Assist with Billing Onboarding", "Customer requires help during onboarding for billing. Offer detailed instructions and ensure smooth setup.", "Neutral", "Jane Smith", "Open", "High", new DateTime(2025, 11, 2), "user183@example.com"),
                new SupportData("TICKET-184", "Feature Enhancement", "Onboarding", "Enhance Onboarding Features", "Customer suggested improvements for onboarding functionality. Review feasibility and plan implementation for better user experience.", "Very Satisfied", "Emily Davis", "Resolved", "Medium", new DateTime(2025, 10, 28), "user184@example.com"),
                new SupportData("TICKET-185", "Onboarding Assistance", "Billing", "Assist with Billing Onboarding", "Customer requires help during onboarding for billing. Offer detailed instructions and ensure smooth setup.", "Very Satisfied", "Emily Davis", "Open", "Urgent", new DateTime(2025, 11, 7), "user185@example.com"),
                new SupportData("TICKET-186", "Refund", "Onboarding", "Handle Onboarding Refund Request", "Customer requested a refund related to onboarding. Validate transaction details and process refund according to policy.", "Very Satisfied", "John Doe", "In Progress", "Urgent", new DateTime(2025, 11, 7), "user186@example.com"),
                new SupportData("TICKET-187", "Onboarding Assistance", "Billing", "Assist with Billing Onboarding", "Customer requires help during onboarding for billing. Offer detailed instructions and ensure smooth setup.", "Satisfied", "Sarah Lee", "Closed", "High", new DateTime(2025, 10, 24), "user187@example.com"),
                new SupportData("TICKET-188", "Bug", "Support", "Resolve Support Bug", "A critical bug has been identified in the support module. Investigate root cause and apply a fix to restore normal functionality promptly.", "Neutral", "Sarah Lee", "In Progress", "High", new DateTime(2025, 10, 30), "user188@example.com"),
                new SupportData("TICKET-189", "Technical Support", "Support", "Provide Support Technical Assistance", "Customer needs Technical Support for support. Diagnose the issue and guide them through resolution steps.", "Neutral", "Jane Smith", "Closed", "Low", new DateTime(2025, 11, 6), "user189@example.com"),
                new SupportData("TICKET-190", "Onboarding Assistance", "Billing", "Assist with Billing Onboarding", "Customer requires help during onboarding for billing. Offer detailed instructions and ensure smooth setup.", "Very Satisfied", "Emily Davis", "Resolved", "High", new DateTime(2025, 10, 25), "user190@example.com"),
                new SupportData("TICKET-191", "Technical Support", "Onboarding", "Provide Onboarding Technical Assistance", "Customer needs Technical Support for onboarding. Diagnose the issue and guide them through resolution steps.", "Neutral", "Tom Wilson", "Open", "Low", new DateTime(2025, 10, 20), "user191@example.com"),
                new SupportData("TICKET-192", "Feature Enhancement", "Product", "Enhance Product Features", "Customer suggested improvements for product functionality. Review feasibility and plan implementation for better user experience.", "Satisfied", "Emily Davis", "Closed", "Medium", new DateTime(2025, 10, 22), "user192@example.com"),
                new SupportData("TICKET-193", "Refund", "Billing", "Handle Billing Refund Request", "Customer requested a refund related to billing. Validate transaction details and process refund according to policy.", "Neutral", "Emily Davis", "In Progress", "Urgent", new DateTime(2025, 11, 13), "user193@example.com"),
                new SupportData("TICKET-194", "Feature Enhancement", "Product", "Enhance Product Features", "Customer suggested improvements for product functionality. Review feasibility and plan implementation for better user experience.", "Very Satisfied", "Tom Wilson", "In Progress", "Urgent", new DateTime(2025, 10, 25), "user194@example.com"),
                new SupportData("TICKET-195", "Subscription Cancellation", "Billing", "Cancel Billing Subscription", "Customer requested cancellation of subscription under billing. Ensure proper termination and confirm via email.", "Very Satisfied", "John Doe", "Open", "Urgent", new DateTime(2025, 10, 31), "user195@example.com"),
                new SupportData("TICKET-196", "Onboarding Assistance", "Onboarding", "Assist with Onboarding Onboarding", "Customer requires help during onboarding for onboarding. Offer detailed instructions and ensure smooth setup.", "Very Satisfied", "Tom Wilson", "Resolved", "Medium", new DateTime(2025, 10, 21), "user196@example.com"),
                new SupportData("TICKET-197", "Onboarding Assistance", "Support", "Assist with Support Onboarding", "Customer requires help during onboarding for support. Offer detailed instructions and ensure smooth setup.", "Satisfied", "Jane Smith", "Open", "High", new DateTime(2025, 10, 28), "user197@example.com"),
                new SupportData("TICKET-198", "Onboarding Assistance", "Billing", "Assist with Billing Onboarding", "Customer requires help during onboarding for billing. Offer detailed instructions and ensure smooth setup.", "Very Satisfied", "John Doe", "Closed", "Low", new DateTime(2025, 10, 29), "user198@example.com"),
                new SupportData("TICKET-199", "Technical Support", "Support", "Provide Support Technical Assistance", "Customer needs Technical Support for support. Diagnose the issue and guide them through resolution steps.", "Neutral", "Jane Smith", "Open", "Medium", new DateTime(2025, 10, 23), "user199@example.com"),
                new SupportData("TICKET-200", "Bug", "Product", "Resolve Product Bug", "A critical bug has been identified in the product module. Investigate root cause and apply a fix to restore normal functionality promptly.", "Satisfied", "Jane Smith", "Resolved", "Urgent", new DateTime(2025, 10, 31), "user200@example.com")
            };
        }

        public string TicketID { get; set; }
        public string TypeOfRequest { get; set; }
        public string Category { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Rating { get; set; }
        public string Assignee { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CustomerEmail { get; set; }
    }
}